
export { default as Aerialway } from './icons/aerialway-11';
import { paths as pathsAerialway } from './icons/aerialway-11';
export { default as Airfield } from './icons/airfield-11';
import { paths as pathsAirfield } from './icons/airfield-11';
export { default as Airport } from './icons/airport-11';
import { paths as pathsAirport } from './icons/airport-11';
export { default as AlcoholShop } from './icons/alcohol-shop-11';
import { paths as pathsAlcoholShop } from './icons/alcohol-shop-11';
export { default as AmericanFootball } from './icons/american-football-11';
import { paths as pathsAmericanFootball } from './icons/american-football-11';
export { default as AmusementPark } from './icons/amusement-park-11';
import { paths as pathsAmusementPark } from './icons/amusement-park-11';
export { default as Aquarium } from './icons/aquarium-11';
import { paths as pathsAquarium } from './icons/aquarium-11';
export { default as ArtGallery } from './icons/art-gallery-11';
import { paths as pathsArtGallery } from './icons/art-gallery-11';
export { default as Attraction } from './icons/attraction-11';
import { paths as pathsAttraction } from './icons/attraction-11';
export { default as Bakery } from './icons/bakery-11';
import { paths as pathsBakery } from './icons/bakery-11';
export { default as Bank } from './icons/bank-11';
import { paths as pathsBank } from './icons/bank-11';
export { default as BankJp } from './icons/bank-JP-11';
import { paths as pathsBankJp } from './icons/bank-JP-11';
export { default as Bar } from './icons/bar-11';
import { paths as pathsBar } from './icons/bar-11';
export { default as Barrier } from './icons/barrier-11';
import { paths as pathsBarrier } from './icons/barrier-11';
export { default as Baseball } from './icons/baseball-11';
import { paths as pathsBaseball } from './icons/baseball-11';
export { default as Basketball } from './icons/basketball-11';
import { paths as pathsBasketball } from './icons/basketball-11';
export { default as Bbq } from './icons/bbq-11';
import { paths as pathsBbq } from './icons/bbq-11';
export { default as Beach } from './icons/beach-11';
import { paths as pathsBeach } from './icons/beach-11';
export { default as Beer } from './icons/beer-11';
import { paths as pathsBeer } from './icons/beer-11';
export { default as Bicycle } from './icons/bicycle-11';
import { paths as pathsBicycle } from './icons/bicycle-11';
export { default as BicycleShare } from './icons/bicycle-share-11';
import { paths as pathsBicycleShare } from './icons/bicycle-share-11';
export { default as BloodBank } from './icons/blood-bank-11';
import { paths as pathsBloodBank } from './icons/blood-bank-11';
export { default as BowlingAlley } from './icons/bowling-alley-11';
import { paths as pathsBowlingAlley } from './icons/bowling-alley-11';
export { default as Bridge } from './icons/bridge-11';
import { paths as pathsBridge } from './icons/bridge-11';
export { default as Building } from './icons/building-11';
import { paths as pathsBuilding } from './icons/building-11';
export { default as BuildingAlt1 } from './icons/building-alt1-11';
import { paths as pathsBuildingAlt1 } from './icons/building-alt1-11';
export { default as Bus } from './icons/bus-11';
import { paths as pathsBus } from './icons/bus-11';
export { default as Cafe } from './icons/cafe-11';
import { paths as pathsCafe } from './icons/cafe-11';
export { default as Campsite } from './icons/campsite-11';
import { paths as pathsCampsite } from './icons/campsite-11';
export { default as Car } from './icons/car-11';
import { paths as pathsCar } from './icons/car-11';
export { default as CarRental } from './icons/car-rental-11';
import { paths as pathsCarRental } from './icons/car-rental-11';
export { default as CarRepair } from './icons/car-repair-11';
import { paths as pathsCarRepair } from './icons/car-repair-11';
export { default as Casino } from './icons/casino-11';
import { paths as pathsCasino } from './icons/casino-11';
export { default as Castle } from './icons/castle-11';
import { paths as pathsCastle } from './icons/castle-11';
export { default as CastleJp } from './icons/castle-JP-11';
import { paths as pathsCastleJp } from './icons/castle-JP-11';
export { default as Cemetery } from './icons/cemetery-11';
import { paths as pathsCemetery } from './icons/cemetery-11';
export { default as CemeteryJp } from './icons/cemetery-JP-11';
import { paths as pathsCemeteryJp } from './icons/cemetery-JP-11';
export { default as ChargingStation } from './icons/charging-station-11';
import { paths as pathsChargingStation } from './icons/charging-station-11';
export { default as Cinema } from './icons/cinema-11';
import { paths as pathsCinema } from './icons/cinema-11';
export { default as Circle } from './icons/circle-11';
import { paths as pathsCircle } from './icons/circle-11';
export { default as CircleStroked } from './icons/circle-stroked-11';
import { paths as pathsCircleStroked } from './icons/circle-stroked-11';
export { default as City } from './icons/city-11';
import { paths as pathsCity } from './icons/city-11';
export { default as ClothingStore } from './icons/clothing-store-11';
import { paths as pathsClothingStore } from './icons/clothing-store-11';
export { default as College } from './icons/college-11';
import { paths as pathsCollege } from './icons/college-11';
export { default as CollegeJp } from './icons/college-JP-11';
import { paths as pathsCollegeJp } from './icons/college-JP-11';
export { default as Commercial } from './icons/commercial-11';
import { paths as pathsCommercial } from './icons/commercial-11';
export { default as CommunicationsTower } from './icons/communications-tower-11';
import { paths as pathsCommunicationsTower } from './icons/communications-tower-11';
export { default as Confectionery } from './icons/confectionery-11';
import { paths as pathsConfectionery } from './icons/confectionery-11';
export { default as Convenience } from './icons/convenience-11';
import { paths as pathsConvenience } from './icons/convenience-11';
export { default as Cricket } from './icons/cricket-11';
import { paths as pathsCricket } from './icons/cricket-11';
export { default as Cross } from './icons/cross-11';
import { paths as pathsCross } from './icons/cross-11';
export { default as Dam } from './icons/dam-11';
import { paths as pathsDam } from './icons/dam-11';
export { default as Danger } from './icons/danger-11';
import { paths as pathsDanger } from './icons/danger-11';
export { default as Defibrillator } from './icons/defibrillator-11';
import { paths as pathsDefibrillator } from './icons/defibrillator-11';
export { default as Dentist } from './icons/dentist-11';
import { paths as pathsDentist } from './icons/dentist-11';
export { default as Doctor } from './icons/doctor-11';
import { paths as pathsDoctor } from './icons/doctor-11';
export { default as DogPark } from './icons/dog-park-11';
import { paths as pathsDogPark } from './icons/dog-park-11';
export { default as DrinkingWater } from './icons/drinking-water-11';
import { paths as pathsDrinkingWater } from './icons/drinking-water-11';
export { default as Embassy } from './icons/embassy-11';
import { paths as pathsEmbassy } from './icons/embassy-11';
export { default as EmergencyPhone } from './icons/emergency-phone-11';
import { paths as pathsEmergencyPhone } from './icons/emergency-phone-11';
export { default as Entrance } from './icons/entrance-11';
import { paths as pathsEntrance } from './icons/entrance-11';
export { default as EntranceAlt1 } from './icons/entrance-alt1-11';
import { paths as pathsEntranceAlt1 } from './icons/entrance-alt1-11';
export { default as Farm } from './icons/farm-11';
import { paths as pathsFarm } from './icons/farm-11';
export { default as FastFood } from './icons/fast-food-11';
import { paths as pathsFastFood } from './icons/fast-food-11';
export { default as Fence } from './icons/fence-11';
import { paths as pathsFence } from './icons/fence-11';
export { default as Ferry } from './icons/ferry-11';
import { paths as pathsFerry } from './icons/ferry-11';
export { default as FireStation } from './icons/fire-station-11';
import { paths as pathsFireStation } from './icons/fire-station-11';
export { default as FireStationJp } from './icons/fire-station-JP-11';
import { paths as pathsFireStationJp } from './icons/fire-station-JP-11';
export { default as FitnessCentre } from './icons/fitness-centre-11';
import { paths as pathsFitnessCentre } from './icons/fitness-centre-11';
export { default as Florist } from './icons/florist-11';
import { paths as pathsFlorist } from './icons/florist-11';
export { default as Fuel } from './icons/fuel-11';
import { paths as pathsFuel } from './icons/fuel-11';
export { default as Furniture } from './icons/furniture-11';
import { paths as pathsFurniture } from './icons/furniture-11';
export { default as Gaming } from './icons/gaming-11';
import { paths as pathsGaming } from './icons/gaming-11';
export { default as Garden } from './icons/garden-11';
import { paths as pathsGarden } from './icons/garden-11';
export { default as GardenCentre } from './icons/garden-centre-11';
import { paths as pathsGardenCentre } from './icons/garden-centre-11';
export { default as Gift } from './icons/gift-11';
import { paths as pathsGift } from './icons/gift-11';
export { default as Globe } from './icons/globe-11';
import { paths as pathsGlobe } from './icons/globe-11';
export { default as Golf } from './icons/golf-11';
import { paths as pathsGolf } from './icons/golf-11';
export { default as Grocery } from './icons/grocery-11';
import { paths as pathsGrocery } from './icons/grocery-11';
export { default as Hairdresser } from './icons/hairdresser-11';
import { paths as pathsHairdresser } from './icons/hairdresser-11';
export { default as Harbor } from './icons/harbor-11';
import { paths as pathsHarbor } from './icons/harbor-11';
export { default as Hardware } from './icons/hardware-11';
import { paths as pathsHardware } from './icons/hardware-11';
export { default as Heart } from './icons/heart-11';
import { paths as pathsHeart } from './icons/heart-11';
export { default as Heliport } from './icons/heliport-11';
import { paths as pathsHeliport } from './icons/heliport-11';
export { default as Home } from './icons/home-11';
import { paths as pathsHome } from './icons/home-11';
export { default as HorseRiding } from './icons/horse-riding-11';
import { paths as pathsHorseRiding } from './icons/horse-riding-11';
export { default as Hospital } from './icons/hospital-11';
import { paths as pathsHospital } from './icons/hospital-11';
export { default as HospitalJp } from './icons/hospital-JP-11';
import { paths as pathsHospitalJp } from './icons/hospital-JP-11';
export { default as IceCream } from './icons/ice-cream-11';
import { paths as pathsIceCream } from './icons/ice-cream-11';
export { default as Industry } from './icons/industry-11';
import { paths as pathsIndustry } from './icons/industry-11';
export { default as Information } from './icons/information-11';
import { paths as pathsInformation } from './icons/information-11';
export { default as JewelryStore } from './icons/jewelry-store-11';
import { paths as pathsJewelryStore } from './icons/jewelry-store-11';
export { default as Karaoke } from './icons/karaoke-11';
import { paths as pathsKaraoke } from './icons/karaoke-11';
export { default as Landmark } from './icons/landmark-11';
import { paths as pathsLandmark } from './icons/landmark-11';
export { default as LandmarkJp } from './icons/landmark-JP-11';
import { paths as pathsLandmarkJp } from './icons/landmark-JP-11';
export { default as Landuse } from './icons/landuse-11';
import { paths as pathsLanduse } from './icons/landuse-11';
export { default as Laundry } from './icons/laundry-11';
import { paths as pathsLaundry } from './icons/laundry-11';
export { default as Library } from './icons/library-11';
import { paths as pathsLibrary } from './icons/library-11';
export { default as Lighthouse } from './icons/lighthouse-11';
import { paths as pathsLighthouse } from './icons/lighthouse-11';
export { default as Lodging } from './icons/lodging-11';
import { paths as pathsLodging } from './icons/lodging-11';
export { default as Logging } from './icons/logging-11';
import { paths as pathsLogging } from './icons/logging-11';
export { default as Marker } from './icons/marker-11';
import { paths as pathsMarker } from './icons/marker-11';
export { default as MarkerStroked } from './icons/marker-stroked-11';
import { paths as pathsMarkerStroked } from './icons/marker-stroked-11';
export { default as MobilePhone } from './icons/mobile-phone-11';
import { paths as pathsMobilePhone } from './icons/mobile-phone-11';
export { default as Monument } from './icons/monument-11';
import { paths as pathsMonument } from './icons/monument-11';
export { default as Mountain } from './icons/mountain-11';
import { paths as pathsMountain } from './icons/mountain-11';
export { default as Museum } from './icons/museum-11';
import { paths as pathsMuseum } from './icons/museum-11';
export { default as Music } from './icons/music-11';
import { paths as pathsMusic } from './icons/music-11';
export { default as Natural } from './icons/natural-11';
import { paths as pathsNatural } from './icons/natural-11';
export { default as Optician } from './icons/optician-11';
import { paths as pathsOptician } from './icons/optician-11';
export { default as Paint } from './icons/paint-11';
import { paths as pathsPaint } from './icons/paint-11';
export { default as Park } from './icons/park-11';
import { paths as pathsPark } from './icons/park-11';
export { default as ParkAlt1 } from './icons/park-alt1-11';
import { paths as pathsParkAlt1 } from './icons/park-alt1-11';
export { default as Parking } from './icons/parking-11';
import { paths as pathsParking } from './icons/parking-11';
export { default as ParkingGarage } from './icons/parking-garage-11';
import { paths as pathsParkingGarage } from './icons/parking-garage-11';
export { default as Pharmacy } from './icons/pharmacy-11';
import { paths as pathsPharmacy } from './icons/pharmacy-11';
export { default as PicnicSite } from './icons/picnic-site-11';
import { paths as pathsPicnicSite } from './icons/picnic-site-11';
export { default as Pitch } from './icons/pitch-11';
import { paths as pathsPitch } from './icons/pitch-11';
export { default as PlaceOfWorship } from './icons/place-of-worship-11';
import { paths as pathsPlaceOfWorship } from './icons/place-of-worship-11';
export { default as Playground } from './icons/playground-11';
import { paths as pathsPlayground } from './icons/playground-11';
export { default as Police } from './icons/police-11';
import { paths as pathsPolice } from './icons/police-11';
export { default as PoliceJp } from './icons/police-JP-11';
import { paths as pathsPoliceJp } from './icons/police-JP-11';
export { default as Post } from './icons/post-11';
import { paths as pathsPost } from './icons/post-11';
export { default as PostJp } from './icons/post-JP-11';
import { paths as pathsPostJp } from './icons/post-JP-11';
export { default as Prison } from './icons/prison-11';
import { paths as pathsPrison } from './icons/prison-11';
export { default as Rail } from './icons/rail-11';
import { paths as pathsRail } from './icons/rail-11';
export { default as RailLight } from './icons/rail-light-11';
import { paths as pathsRailLight } from './icons/rail-light-11';
export { default as RailMetro } from './icons/rail-metro-11';
import { paths as pathsRailMetro } from './icons/rail-metro-11';
export { default as RangerStation } from './icons/ranger-station-11';
import { paths as pathsRangerStation } from './icons/ranger-station-11';
export { default as Recycling } from './icons/recycling-11';
import { paths as pathsRecycling } from './icons/recycling-11';
export { default as ReligiousBuddhist } from './icons/religious-buddhist-11';
import { paths as pathsReligiousBuddhist } from './icons/religious-buddhist-11';
export { default as ReligiousChristian } from './icons/religious-christian-11';
import { paths as pathsReligiousChristian } from './icons/religious-christian-11';
export { default as ReligiousJewish } from './icons/religious-jewish-11';
import { paths as pathsReligiousJewish } from './icons/religious-jewish-11';
export { default as ReligiousMuslim } from './icons/religious-muslim-11';
import { paths as pathsReligiousMuslim } from './icons/religious-muslim-11';
export { default as ReligiousShinto } from './icons/religious-shinto-11';
import { paths as pathsReligiousShinto } from './icons/religious-shinto-11';
export { default as ResidentialCommunity } from './icons/residential-community-11';
import { paths as pathsResidentialCommunity } from './icons/residential-community-11';
export { default as Restaurant } from './icons/restaurant-11';
import { paths as pathsRestaurant } from './icons/restaurant-11';
export { default as RestaurantNoodle } from './icons/restaurant-noodle-11';
import { paths as pathsRestaurantNoodle } from './icons/restaurant-noodle-11';
export { default as RestaurantPizza } from './icons/restaurant-pizza-11';
import { paths as pathsRestaurantPizza } from './icons/restaurant-pizza-11';
export { default as RestaurantSeafood } from './icons/restaurant-seafood-11';
import { paths as pathsRestaurantSeafood } from './icons/restaurant-seafood-11';
export { default as Roadblock } from './icons/roadblock-11';
import { paths as pathsRoadblock } from './icons/roadblock-11';
export { default as Rocket } from './icons/rocket-11';
import { paths as pathsRocket } from './icons/rocket-11';
export { default as School } from './icons/school-11';
import { paths as pathsSchool } from './icons/school-11';
export { default as SchoolJp } from './icons/school-JP-11';
import { paths as pathsSchoolJp } from './icons/school-JP-11';
export { default as Scooter } from './icons/scooter-11';
import { paths as pathsScooter } from './icons/scooter-11';
export { default as Shelter } from './icons/shelter-11';
import { paths as pathsShelter } from './icons/shelter-11';
export { default as Shoe } from './icons/shoe-11';
import { paths as pathsShoe } from './icons/shoe-11';
export { default as Shop } from './icons/shop-11';
import { paths as pathsShop } from './icons/shop-11';
export { default as Skateboard } from './icons/skateboard-11';
import { paths as pathsSkateboard } from './icons/skateboard-11';
export { default as Skiing } from './icons/skiing-11';
import { paths as pathsSkiing } from './icons/skiing-11';
export { default as Slaughterhouse } from './icons/slaughterhouse-11';
import { paths as pathsSlaughterhouse } from './icons/slaughterhouse-11';
export { default as Slipway } from './icons/slipway-11';
import { paths as pathsSlipway } from './icons/slipway-11';
export { default as Snowmobile } from './icons/snowmobile-11';
import { paths as pathsSnowmobile } from './icons/snowmobile-11';
export { default as Soccer } from './icons/soccer-11';
import { paths as pathsSoccer } from './icons/soccer-11';
export { default as Square } from './icons/square-11';
import { paths as pathsSquare } from './icons/square-11';
export { default as SquareStroked } from './icons/square-stroked-11';
import { paths as pathsSquareStroked } from './icons/square-stroked-11';
export { default as Stadium } from './icons/stadium-11';
import { paths as pathsStadium } from './icons/stadium-11';
export { default as Star } from './icons/star-11';
import { paths as pathsStar } from './icons/star-11';
export { default as StarStroked } from './icons/star-stroked-11';
import { paths as pathsStarStroked } from './icons/star-stroked-11';
export { default as Suitcase } from './icons/suitcase-11';
import { paths as pathsSuitcase } from './icons/suitcase-11';
export { default as Sushi } from './icons/sushi-11';
import { paths as pathsSushi } from './icons/sushi-11';
export { default as Swimming } from './icons/swimming-11';
import { paths as pathsSwimming } from './icons/swimming-11';
export { default as TableTennis } from './icons/table-tennis-11';
import { paths as pathsTableTennis } from './icons/table-tennis-11';
export { default as Teahouse } from './icons/teahouse-11';
import { paths as pathsTeahouse } from './icons/teahouse-11';
export { default as Telephone } from './icons/telephone-11';
import { paths as pathsTelephone } from './icons/telephone-11';
export { default as Tennis } from './icons/tennis-11';
import { paths as pathsTennis } from './icons/tennis-11';
export { default as Theatre } from './icons/theatre-11';
import { paths as pathsTheatre } from './icons/theatre-11';
export { default as Toilet } from './icons/toilet-11';
import { paths as pathsToilet } from './icons/toilet-11';
export { default as Town } from './icons/town-11';
import { paths as pathsTown } from './icons/town-11';
export { default as TownHall } from './icons/town-hall-11';
import { paths as pathsTownHall } from './icons/town-hall-11';
export { default as Triangle } from './icons/triangle-11';
import { paths as pathsTriangle } from './icons/triangle-11';
export { default as TriangleStroked } from './icons/triangle-stroked-11';
import { paths as pathsTriangleStroked } from './icons/triangle-stroked-11';
export { default as Veterinary } from './icons/veterinary-11';
import { paths as pathsVeterinary } from './icons/veterinary-11';
export { default as Viewpoint } from './icons/viewpoint-11';
import { paths as pathsViewpoint } from './icons/viewpoint-11';
export { default as Village } from './icons/village-11';
import { paths as pathsVillage } from './icons/village-11';
export { default as Volcano } from './icons/volcano-11';
import { paths as pathsVolcano } from './icons/volcano-11';
export { default as Volleyball } from './icons/volleyball-11';
import { paths as pathsVolleyball } from './icons/volleyball-11';
export { default as Warehouse } from './icons/warehouse-11';
import { paths as pathsWarehouse } from './icons/warehouse-11';
export { default as WasteBasket } from './icons/waste-basket-11';
import { paths as pathsWasteBasket } from './icons/waste-basket-11';
export { default as Watch } from './icons/watch-11';
import { paths as pathsWatch } from './icons/watch-11';
export { default as Water } from './icons/water-11';
import { paths as pathsWater } from './icons/water-11';
export { default as Waterfall } from './icons/waterfall-11';
import { paths as pathsWaterfall } from './icons/waterfall-11';
export { default as Watermill } from './icons/watermill-11';
import { paths as pathsWatermill } from './icons/watermill-11';
export { default as Wetland } from './icons/wetland-11';
import { paths as pathsWetland } from './icons/wetland-11';
export { default as Wheelchair } from './icons/wheelchair-11';
import { paths as pathsWheelchair } from './icons/wheelchair-11';
export { default as Windmill } from './icons/windmill-11';
import { paths as pathsWindmill } from './icons/windmill-11';
export { default as Zoo } from './icons/zoo-11';
import { paths as pathsZoo } from './icons/zoo-11';
type PathsMap = {
  [key:string]: {
    paths: string[]
  }
}
const paths:PathsMap = {};
paths['aerialway'] = { paths: pathsAerialway };
paths['airfield'] = { paths: pathsAirfield };
paths['airport'] = { paths: pathsAirport };
paths['alcohol-shop'] = { paths: pathsAlcoholShop };
paths['american-football'] = { paths: pathsAmericanFootball };
paths['amusement-park'] = { paths: pathsAmusementPark };
paths['aquarium'] = { paths: pathsAquarium };
paths['art-gallery'] = { paths: pathsArtGallery };
paths['attraction'] = { paths: pathsAttraction };
paths['bakery'] = { paths: pathsBakery };
paths['bank'] = { paths: pathsBank };
paths['bank-JP'] = { paths: pathsBankJp };
paths['bar'] = { paths: pathsBar };
paths['barrier'] = { paths: pathsBarrier };
paths['baseball'] = { paths: pathsBaseball };
paths['basketball'] = { paths: pathsBasketball };
paths['bbq'] = { paths: pathsBbq };
paths['beach'] = { paths: pathsBeach };
paths['beer'] = { paths: pathsBeer };
paths['bicycle'] = { paths: pathsBicycle };
paths['bicycle-share'] = { paths: pathsBicycleShare };
paths['blood-bank'] = { paths: pathsBloodBank };
paths['bowling-alley'] = { paths: pathsBowlingAlley };
paths['bridge'] = { paths: pathsBridge };
paths['building'] = { paths: pathsBuilding };
paths['building-alt1'] = { paths: pathsBuildingAlt1 };
paths['bus'] = { paths: pathsBus };
paths['cafe'] = { paths: pathsCafe };
paths['campsite'] = { paths: pathsCampsite };
paths['car'] = { paths: pathsCar };
paths['car-rental'] = { paths: pathsCarRental };
paths['car-repair'] = { paths: pathsCarRepair };
paths['casino'] = { paths: pathsCasino };
paths['castle'] = { paths: pathsCastle };
paths['castle-JP'] = { paths: pathsCastleJp };
paths['cemetery'] = { paths: pathsCemetery };
paths['cemetery-JP'] = { paths: pathsCemeteryJp };
paths['charging-station'] = { paths: pathsChargingStation };
paths['cinema'] = { paths: pathsCinema };
paths['circle'] = { paths: pathsCircle };
paths['circle-stroked'] = { paths: pathsCircleStroked };
paths['city'] = { paths: pathsCity };
paths['clothing-store'] = { paths: pathsClothingStore };
paths['college'] = { paths: pathsCollege };
paths['college-JP'] = { paths: pathsCollegeJp };
paths['commercial'] = { paths: pathsCommercial };
paths['communications-tower'] = { paths: pathsCommunicationsTower };
paths['confectionery'] = { paths: pathsConfectionery };
paths['convenience'] = { paths: pathsConvenience };
paths['cricket'] = { paths: pathsCricket };
paths['cross'] = { paths: pathsCross };
paths['dam'] = { paths: pathsDam };
paths['danger'] = { paths: pathsDanger };
paths['defibrillator'] = { paths: pathsDefibrillator };
paths['dentist'] = { paths: pathsDentist };
paths['doctor'] = { paths: pathsDoctor };
paths['dog-park'] = { paths: pathsDogPark };
paths['drinking-water'] = { paths: pathsDrinkingWater };
paths['embassy'] = { paths: pathsEmbassy };
paths['emergency-phone'] = { paths: pathsEmergencyPhone };
paths['entrance'] = { paths: pathsEntrance };
paths['entrance-alt1'] = { paths: pathsEntranceAlt1 };
paths['farm'] = { paths: pathsFarm };
paths['fast-food'] = { paths: pathsFastFood };
paths['fence'] = { paths: pathsFence };
paths['ferry'] = { paths: pathsFerry };
paths['fire-station'] = { paths: pathsFireStation };
paths['fire-station-JP'] = { paths: pathsFireStationJp };
paths['fitness-centre'] = { paths: pathsFitnessCentre };
paths['florist'] = { paths: pathsFlorist };
paths['fuel'] = { paths: pathsFuel };
paths['furniture'] = { paths: pathsFurniture };
paths['gaming'] = { paths: pathsGaming };
paths['garden'] = { paths: pathsGarden };
paths['garden-centre'] = { paths: pathsGardenCentre };
paths['gift'] = { paths: pathsGift };
paths['globe'] = { paths: pathsGlobe };
paths['golf'] = { paths: pathsGolf };
paths['grocery'] = { paths: pathsGrocery };
paths['hairdresser'] = { paths: pathsHairdresser };
paths['harbor'] = { paths: pathsHarbor };
paths['hardware'] = { paths: pathsHardware };
paths['heart'] = { paths: pathsHeart };
paths['heliport'] = { paths: pathsHeliport };
paths['home'] = { paths: pathsHome };
paths['horse-riding'] = { paths: pathsHorseRiding };
paths['hospital'] = { paths: pathsHospital };
paths['hospital-JP'] = { paths: pathsHospitalJp };
paths['ice-cream'] = { paths: pathsIceCream };
paths['industry'] = { paths: pathsIndustry };
paths['information'] = { paths: pathsInformation };
paths['jewelry-store'] = { paths: pathsJewelryStore };
paths['karaoke'] = { paths: pathsKaraoke };
paths['landmark'] = { paths: pathsLandmark };
paths['landmark-JP'] = { paths: pathsLandmarkJp };
paths['landuse'] = { paths: pathsLanduse };
paths['laundry'] = { paths: pathsLaundry };
paths['library'] = { paths: pathsLibrary };
paths['lighthouse'] = { paths: pathsLighthouse };
paths['lodging'] = { paths: pathsLodging };
paths['logging'] = { paths: pathsLogging };
paths['marker'] = { paths: pathsMarker };
paths['marker-stroked'] = { paths: pathsMarkerStroked };
paths['mobile-phone'] = { paths: pathsMobilePhone };
paths['monument'] = { paths: pathsMonument };
paths['mountain'] = { paths: pathsMountain };
paths['museum'] = { paths: pathsMuseum };
paths['music'] = { paths: pathsMusic };
paths['natural'] = { paths: pathsNatural };
paths['optician'] = { paths: pathsOptician };
paths['paint'] = { paths: pathsPaint };
paths['park'] = { paths: pathsPark };
paths['park-alt1'] = { paths: pathsParkAlt1 };
paths['parking'] = { paths: pathsParking };
paths['parking-garage'] = { paths: pathsParkingGarage };
paths['pharmacy'] = { paths: pathsPharmacy };
paths['picnic-site'] = { paths: pathsPicnicSite };
paths['pitch'] = { paths: pathsPitch };
paths['place-of-worship'] = { paths: pathsPlaceOfWorship };
paths['playground'] = { paths: pathsPlayground };
paths['police'] = { paths: pathsPolice };
paths['police-JP'] = { paths: pathsPoliceJp };
paths['post'] = { paths: pathsPost };
paths['post-JP'] = { paths: pathsPostJp };
paths['prison'] = { paths: pathsPrison };
paths['rail'] = { paths: pathsRail };
paths['rail-light'] = { paths: pathsRailLight };
paths['rail-metro'] = { paths: pathsRailMetro };
paths['ranger-station'] = { paths: pathsRangerStation };
paths['recycling'] = { paths: pathsRecycling };
paths['religious-buddhist'] = { paths: pathsReligiousBuddhist };
paths['religious-christian'] = { paths: pathsReligiousChristian };
paths['religious-jewish'] = { paths: pathsReligiousJewish };
paths['religious-muslim'] = { paths: pathsReligiousMuslim };
paths['religious-shinto'] = { paths: pathsReligiousShinto };
paths['residential-community'] = { paths: pathsResidentialCommunity };
paths['restaurant'] = { paths: pathsRestaurant };
paths['restaurant-noodle'] = { paths: pathsRestaurantNoodle };
paths['restaurant-pizza'] = { paths: pathsRestaurantPizza };
paths['restaurant-seafood'] = { paths: pathsRestaurantSeafood };
paths['roadblock'] = { paths: pathsRoadblock };
paths['rocket'] = { paths: pathsRocket };
paths['school'] = { paths: pathsSchool };
paths['school-JP'] = { paths: pathsSchoolJp };
paths['scooter'] = { paths: pathsScooter };
paths['shelter'] = { paths: pathsShelter };
paths['shoe'] = { paths: pathsShoe };
paths['shop'] = { paths: pathsShop };
paths['skateboard'] = { paths: pathsSkateboard };
paths['skiing'] = { paths: pathsSkiing };
paths['slaughterhouse'] = { paths: pathsSlaughterhouse };
paths['slipway'] = { paths: pathsSlipway };
paths['snowmobile'] = { paths: pathsSnowmobile };
paths['soccer'] = { paths: pathsSoccer };
paths['square'] = { paths: pathsSquare };
paths['square-stroked'] = { paths: pathsSquareStroked };
paths['stadium'] = { paths: pathsStadium };
paths['star'] = { paths: pathsStar };
paths['star-stroked'] = { paths: pathsStarStroked };
paths['suitcase'] = { paths: pathsSuitcase };
paths['sushi'] = { paths: pathsSushi };
paths['swimming'] = { paths: pathsSwimming };
paths['table-tennis'] = { paths: pathsTableTennis };
paths['teahouse'] = { paths: pathsTeahouse };
paths['telephone'] = { paths: pathsTelephone };
paths['tennis'] = { paths: pathsTennis };
paths['theatre'] = { paths: pathsTheatre };
paths['toilet'] = { paths: pathsToilet };
paths['town'] = { paths: pathsTown };
paths['town-hall'] = { paths: pathsTownHall };
paths['triangle'] = { paths: pathsTriangle };
paths['triangle-stroked'] = { paths: pathsTriangleStroked };
paths['veterinary'] = { paths: pathsVeterinary };
paths['viewpoint'] = { paths: pathsViewpoint };
paths['village'] = { paths: pathsVillage };
paths['volcano'] = { paths: pathsVolcano };
paths['volleyball'] = { paths: pathsVolleyball };
paths['warehouse'] = { paths: pathsWarehouse };
paths['waste-basket'] = { paths: pathsWasteBasket };
paths['watch'] = { paths: pathsWatch };
paths['water'] = { paths: pathsWater };
paths['waterfall'] = { paths: pathsWaterfall };
paths['watermill'] = { paths: pathsWatermill };
paths['wetland'] = { paths: pathsWetland };
paths['wheelchair'] = { paths: pathsWheelchair };
paths['windmill'] = { paths: pathsWindmill };
paths['zoo'] = { paths: pathsZoo };
export const iconsMap = paths;
