
import { paths as pathsAerialway } from './icons/aerialway';
import { paths as pathsAirfield } from './icons/airfield';
import { paths as pathsAirport } from './icons/airport';
import { paths as pathsAlcoholShop } from './icons/alcohol-shop';
import { paths as pathsAmericanFootball } from './icons/american-football';
import { paths as pathsAmusementPark } from './icons/amusement-park';
import { paths as pathsAquarium } from './icons/aquarium';
import { paths as pathsArrow } from './icons/arrow';
import { paths as pathsArtGallery } from './icons/art-gallery';
import { paths as pathsAttraction } from './icons/attraction';
import { paths as pathsBakery } from './icons/bakery';
import { paths as pathsBankJp } from './icons/bank-JP';
import { paths as pathsBank } from './icons/bank';
import { paths as pathsBar } from './icons/bar';
import { paths as pathsBarrier } from './icons/barrier';
import { paths as pathsBaseball } from './icons/baseball';
import { paths as pathsBasketball } from './icons/basketball';
import { paths as pathsBbq } from './icons/bbq';
import { paths as pathsBeach } from './icons/beach';
import { paths as pathsBeer } from './icons/beer';
import { paths as pathsBicycleShare } from './icons/bicycle-share';
import { paths as pathsBicycle } from './icons/bicycle';
import { paths as pathsBloodBank } from './icons/blood-bank';
import { paths as pathsBowlingAlley } from './icons/bowling-alley';
import { paths as pathsBridge } from './icons/bridge';
import { paths as pathsBuildingAlt1 } from './icons/building-alt1';
import { paths as pathsBuilding } from './icons/building';
import { paths as pathsBus } from './icons/bus';
import { paths as pathsCafe } from './icons/cafe';
import { paths as pathsCampsite } from './icons/campsite';
import { paths as pathsCarRental } from './icons/car-rental';
import { paths as pathsCarRepair } from './icons/car-repair';
import { paths as pathsCar } from './icons/car';
import { paths as pathsCasino } from './icons/casino';
import { paths as pathsCastleJp } from './icons/castle-JP';
import { paths as pathsCastle } from './icons/castle';
import { paths as pathsCaution } from './icons/caution';
import { paths as pathsCemeteryJp } from './icons/cemetery-JP';
import { paths as pathsCemetery } from './icons/cemetery';
import { paths as pathsChargingStation } from './icons/charging-station';
import { paths as pathsCinema } from './icons/cinema';
import { paths as pathsCircleStroked } from './icons/circle-stroked';
import { paths as pathsCircle } from './icons/circle';
import { paths as pathsCity } from './icons/city';
import { paths as pathsClothingStore } from './icons/clothing-store';
import { paths as pathsCollegeJp } from './icons/college-JP';
import { paths as pathsCollege } from './icons/college';
import { paths as pathsCommercial } from './icons/commercial';
import { paths as pathsCommunicationsTower } from './icons/communications-tower';
import { paths as pathsConfectionery } from './icons/confectionery';
import { paths as pathsConstruction } from './icons/construction';
import { paths as pathsConvenience } from './icons/convenience';
import { paths as pathsCricket } from './icons/cricket';
import { paths as pathsCross } from './icons/cross';
import { paths as pathsDam } from './icons/dam';
import { paths as pathsDanger } from './icons/danger';
import { paths as pathsDefibrillator } from './icons/defibrillator';
import { paths as pathsDentist } from './icons/dentist';
import { paths as pathsDiamond } from './icons/diamond';
import { paths as pathsDoctor } from './icons/doctor';
import { paths as pathsDogPark } from './icons/dog-park';
import { paths as pathsDrinkingWater } from './icons/drinking-water';
import { paths as pathsElevator } from './icons/elevator';
import { paths as pathsEmbassy } from './icons/embassy';
import { paths as pathsEmergencyPhone } from './icons/emergency-phone';
import { paths as pathsEntranceAlt1 } from './icons/entrance-alt1';
import { paths as pathsEntrance } from './icons/entrance';
import { paths as pathsFarm } from './icons/farm';
import { paths as pathsFastFood } from './icons/fast-food';
import { paths as pathsFence } from './icons/fence';
import { paths as pathsFerryJp } from './icons/ferry-JP';
import { paths as pathsFerry } from './icons/ferry';
import { paths as pathsFireStationJp } from './icons/fire-station-JP';
import { paths as pathsFireStation } from './icons/fire-station';
import { paths as pathsFitnessCentre } from './icons/fitness-centre';
import { paths as pathsFlorist } from './icons/florist';
import { paths as pathsFuel } from './icons/fuel';
import { paths as pathsFurniture } from './icons/furniture';
import { paths as pathsGaming } from './icons/gaming';
import { paths as pathsGardenCentre } from './icons/garden-centre';
import { paths as pathsGarden } from './icons/garden';
import { paths as pathsGift } from './icons/gift';
import { paths as pathsGlobe } from './icons/globe';
import { paths as pathsGolf } from './icons/golf';
import { paths as pathsGrocery } from './icons/grocery';
import { paths as pathsHairdresser } from './icons/hairdresser';
import { paths as pathsHarbor } from './icons/harbor';
import { paths as pathsHardware } from './icons/hardware';
import { paths as pathsHeart } from './icons/heart';
import { paths as pathsHeliport } from './icons/heliport';
import { paths as pathsHighwayRestArea } from './icons/highway-rest-area';
import { paths as pathsHome } from './icons/home';
import { paths as pathsHorseRiding } from './icons/horse-riding';
import { paths as pathsHospitalJp } from './icons/hospital-JP';
import { paths as pathsHospital } from './icons/hospital';
import { paths as pathsHotSpring } from './icons/hot-spring';
import { paths as pathsIceCream } from './icons/ice-cream';
import { paths as pathsIndustry } from './icons/industry';
import { paths as pathsInformation } from './icons/information';
import { paths as pathsJewelryStore } from './icons/jewelry-store';
import { paths as pathsKaraoke } from './icons/karaoke';
import { paths as pathsLandmarkJp } from './icons/landmark-JP';
import { paths as pathsLandmark } from './icons/landmark';
import { paths as pathsLanduse } from './icons/landuse';
import { paths as pathsLaundry } from './icons/laundry';
import { paths as pathsLibrary } from './icons/library';
import { paths as pathsLighthouseJp } from './icons/lighthouse-JP';
import { paths as pathsLighthouse } from './icons/lighthouse';
import { paths as pathsLodging } from './icons/lodging';
import { paths as pathsLogging } from './icons/logging';
import { paths as pathsMarkerStroked } from './icons/marker-stroked';
import { paths as pathsMarker } from './icons/marker';
import { paths as pathsMobilePhone } from './icons/mobile-phone';
import { paths as pathsMonumentJp } from './icons/monument-JP';
import { paths as pathsMonument } from './icons/monument';
import { paths as pathsMountain } from './icons/mountain';
import { paths as pathsMuseum } from './icons/museum';
import { paths as pathsMusic } from './icons/music';
import { paths as pathsNatural } from './icons/natural';
import { paths as pathsObservationTower } from './icons/observation-tower';
import { paths as pathsOptician } from './icons/optician';
import { paths as pathsPaint } from './icons/paint';
import { paths as pathsParkAlt1 } from './icons/park-alt1';
import { paths as pathsPark } from './icons/park';
import { paths as pathsParkingGarage } from './icons/parking-garage';
import { paths as pathsParking } from './icons/parking';
import { paths as pathsPharmacy } from './icons/pharmacy';
import { paths as pathsPicnicSite } from './icons/picnic-site';
import { paths as pathsPitch } from './icons/pitch';
import { paths as pathsPlaceOfWorship } from './icons/place-of-worship';
import { paths as pathsPlayground } from './icons/playground';
import { paths as pathsPoliceJp } from './icons/police-JP';
import { paths as pathsPolice } from './icons/police';
import { paths as pathsPostJp } from './icons/post-JP';
import { paths as pathsPost } from './icons/post';
import { paths as pathsPrison } from './icons/prison';
import { paths as pathsRacetrackBoat } from './icons/racetrack-boat';
import { paths as pathsRacetrackCycling } from './icons/racetrack-cycling';
import { paths as pathsRacetrackHorse } from './icons/racetrack-horse';
import { paths as pathsRacetrack } from './icons/racetrack';
import { paths as pathsRailLight } from './icons/rail-light';
import { paths as pathsRailMetro } from './icons/rail-metro';
import { paths as pathsRail } from './icons/rail';
import { paths as pathsRangerStation } from './icons/ranger-station';
import { paths as pathsRecycling } from './icons/recycling';
import { paths as pathsReligiousBuddhist } from './icons/religious-buddhist';
import { paths as pathsReligiousChristian } from './icons/religious-christian';
import { paths as pathsReligiousJewish } from './icons/religious-jewish';
import { paths as pathsReligiousMuslim } from './icons/religious-muslim';
import { paths as pathsReligiousShinto } from './icons/religious-shinto';
import { paths as pathsResidentialCommunity } from './icons/residential-community';
import { paths as pathsRestaurantBbq } from './icons/restaurant-bbq';
import { paths as pathsRestaurantNoodle } from './icons/restaurant-noodle';
import { paths as pathsRestaurantPizza } from './icons/restaurant-pizza';
import { paths as pathsRestaurantSeafood } from './icons/restaurant-seafood';
import { paths as pathsRestaurantSushi } from './icons/restaurant-sushi';
import { paths as pathsRestaurant } from './icons/restaurant';
import { paths as pathsRoadAccident } from './icons/road-accident';
import { paths as pathsRoadblock } from './icons/roadblock';
import { paths as pathsRocket } from './icons/rocket';
import { paths as pathsSchoolJp } from './icons/school-JP';
import { paths as pathsSchool } from './icons/school';
import { paths as pathsScooter } from './icons/scooter';
import { paths as pathsShelter } from './icons/shelter';
import { paths as pathsShoe } from './icons/shoe';
import { paths as pathsShop } from './icons/shop';
import { paths as pathsSkateboard } from './icons/skateboard';
import { paths as pathsSkiing } from './icons/skiing';
import { paths as pathsSlaughterhouse } from './icons/slaughterhouse';
import { paths as pathsSlipway } from './icons/slipway';
import { paths as pathsSnowmobile } from './icons/snowmobile';
import { paths as pathsSoccer } from './icons/soccer';
import { paths as pathsSquareStroked } from './icons/square-stroked';
import { paths as pathsSquare } from './icons/square';
import { paths as pathsStadium } from './icons/stadium';
import { paths as pathsStarStroked } from './icons/star-stroked';
import { paths as pathsStar } from './icons/star';
import { paths as pathsSuitcase } from './icons/suitcase';
import { paths as pathsSwimming } from './icons/swimming';
import { paths as pathsTableTennis } from './icons/table-tennis';
import { paths as pathsTeahouse } from './icons/teahouse';
import { paths as pathsTelephone } from './icons/telephone';
import { paths as pathsTennis } from './icons/tennis';
import { paths as pathsTheatre } from './icons/theatre';
import { paths as pathsToilet } from './icons/toilet';
import { paths as pathsTownHall } from './icons/town-hall';
import { paths as pathsTown } from './icons/town';
import { paths as pathsTriangleStroked } from './icons/triangle-stroked';
import { paths as pathsTriangle } from './icons/triangle';
import { paths as pathsVeterinary } from './icons/veterinary';
import { paths as pathsViewpoint } from './icons/viewpoint';
import { paths as pathsVillage } from './icons/village';
import { paths as pathsVolcano } from './icons/volcano';
import { paths as pathsVolleyball } from './icons/volleyball';
import { paths as pathsWarehouse } from './icons/warehouse';
import { paths as pathsWasteBasket } from './icons/waste-basket';
import { paths as pathsWatch } from './icons/watch';
import { paths as pathsWater } from './icons/water';
import { paths as pathsWaterfall } from './icons/waterfall';
import { paths as pathsWatermill } from './icons/watermill';
import { paths as pathsWetland } from './icons/wetland';
import { paths as pathsWheelchair } from './icons/wheelchair';
import { paths as pathsWindmill } from './icons/windmill';
import { paths as pathsZoo } from './icons/zoo';
export { default as Aerialway } from './icons/aerialway';
export { default as Airfield } from './icons/airfield';
export { default as Airport } from './icons/airport';
export { default as AlcoholShop } from './icons/alcohol-shop';
export { default as AmericanFootball } from './icons/american-football';
export { default as AmusementPark } from './icons/amusement-park';
export { default as Aquarium } from './icons/aquarium';
export { default as Arrow } from './icons/arrow';
export { default as ArtGallery } from './icons/art-gallery';
export { default as Attraction } from './icons/attraction';
export { default as Bakery } from './icons/bakery';
export { default as BankJp } from './icons/bank-JP';
export { default as Bank } from './icons/bank';
export { default as Bar } from './icons/bar';
export { default as Barrier } from './icons/barrier';
export { default as Baseball } from './icons/baseball';
export { default as Basketball } from './icons/basketball';
export { default as Bbq } from './icons/bbq';
export { default as Beach } from './icons/beach';
export { default as Beer } from './icons/beer';
export { default as BicycleShare } from './icons/bicycle-share';
export { default as Bicycle } from './icons/bicycle';
export { default as BloodBank } from './icons/blood-bank';
export { default as BowlingAlley } from './icons/bowling-alley';
export { default as Bridge } from './icons/bridge';
export { default as BuildingAlt1 } from './icons/building-alt1';
export { default as Building } from './icons/building';
export { default as Bus } from './icons/bus';
export { default as Cafe } from './icons/cafe';
export { default as Campsite } from './icons/campsite';
export { default as CarRental } from './icons/car-rental';
export { default as CarRepair } from './icons/car-repair';
export { default as Car } from './icons/car';
export { default as Casino } from './icons/casino';
export { default as CastleJp } from './icons/castle-JP';
export { default as Castle } from './icons/castle';
export { default as Caution } from './icons/caution';
export { default as CemeteryJp } from './icons/cemetery-JP';
export { default as Cemetery } from './icons/cemetery';
export { default as ChargingStation } from './icons/charging-station';
export { default as Cinema } from './icons/cinema';
export { default as CircleStroked } from './icons/circle-stroked';
export { default as Circle } from './icons/circle';
export { default as City } from './icons/city';
export { default as ClothingStore } from './icons/clothing-store';
export { default as CollegeJp } from './icons/college-JP';
export { default as College } from './icons/college';
export { default as Commercial } from './icons/commercial';
export { default as CommunicationsTower } from './icons/communications-tower';
export { default as Confectionery } from './icons/confectionery';
export { default as Construction } from './icons/construction';
export { default as Convenience } from './icons/convenience';
export { default as Cricket } from './icons/cricket';
export { default as Cross } from './icons/cross';
export { default as Dam } from './icons/dam';
export { default as Danger } from './icons/danger';
export { default as Defibrillator } from './icons/defibrillator';
export { default as Dentist } from './icons/dentist';
export { default as Diamond } from './icons/diamond';
export { default as Doctor } from './icons/doctor';
export { default as DogPark } from './icons/dog-park';
export { default as DrinkingWater } from './icons/drinking-water';
export { default as Elevator } from './icons/elevator';
export { default as Embassy } from './icons/embassy';
export { default as EmergencyPhone } from './icons/emergency-phone';
export { default as EntranceAlt1 } from './icons/entrance-alt1';
export { default as Entrance } from './icons/entrance';
export { default as Farm } from './icons/farm';
export { default as FastFood } from './icons/fast-food';
export { default as Fence } from './icons/fence';
export { default as FerryJp } from './icons/ferry-JP';
export { default as Ferry } from './icons/ferry';
export { default as FireStationJp } from './icons/fire-station-JP';
export { default as FireStation } from './icons/fire-station';
export { default as FitnessCentre } from './icons/fitness-centre';
export { default as Florist } from './icons/florist';
export { default as Fuel } from './icons/fuel';
export { default as Furniture } from './icons/furniture';
export { default as Gaming } from './icons/gaming';
export { default as GardenCentre } from './icons/garden-centre';
export { default as Garden } from './icons/garden';
export { default as Gift } from './icons/gift';
export { default as Globe } from './icons/globe';
export { default as Golf } from './icons/golf';
export { default as Grocery } from './icons/grocery';
export { default as Hairdresser } from './icons/hairdresser';
export { default as Harbor } from './icons/harbor';
export { default as Hardware } from './icons/hardware';
export { default as Heart } from './icons/heart';
export { default as Heliport } from './icons/heliport';
export { default as HighwayRestArea } from './icons/highway-rest-area';
export { default as Home } from './icons/home';
export { default as HorseRiding } from './icons/horse-riding';
export { default as HospitalJp } from './icons/hospital-JP';
export { default as Hospital } from './icons/hospital';
export { default as HotSpring } from './icons/hot-spring';
export { default as IceCream } from './icons/ice-cream';
export { default as Industry } from './icons/industry';
export { default as Information } from './icons/information';
export { default as JewelryStore } from './icons/jewelry-store';
export { default as Karaoke } from './icons/karaoke';
export { default as LandmarkJp } from './icons/landmark-JP';
export { default as Landmark } from './icons/landmark';
export { default as Landuse } from './icons/landuse';
export { default as Laundry } from './icons/laundry';
export { default as Library } from './icons/library';
export { default as LighthouseJp } from './icons/lighthouse-JP';
export { default as Lighthouse } from './icons/lighthouse';
export { default as Lodging } from './icons/lodging';
export { default as Logging } from './icons/logging';
export { default as MarkerStroked } from './icons/marker-stroked';
export { default as Marker } from './icons/marker';
export { default as MobilePhone } from './icons/mobile-phone';
export { default as MonumentJp } from './icons/monument-JP';
export { default as Monument } from './icons/monument';
export { default as Mountain } from './icons/mountain';
export { default as Museum } from './icons/museum';
export { default as Music } from './icons/music';
export { default as Natural } from './icons/natural';
export { default as ObservationTower } from './icons/observation-tower';
export { default as Optician } from './icons/optician';
export { default as Paint } from './icons/paint';
export { default as ParkAlt1 } from './icons/park-alt1';
export { default as Park } from './icons/park';
export { default as ParkingGarage } from './icons/parking-garage';
export { default as Parking } from './icons/parking';
export { default as Pharmacy } from './icons/pharmacy';
export { default as PicnicSite } from './icons/picnic-site';
export { default as Pitch } from './icons/pitch';
export { default as PlaceOfWorship } from './icons/place-of-worship';
export { default as Playground } from './icons/playground';
export { default as PoliceJp } from './icons/police-JP';
export { default as Police } from './icons/police';
export { default as PostJp } from './icons/post-JP';
export { default as Post } from './icons/post';
export { default as Prison } from './icons/prison';
export { default as RacetrackBoat } from './icons/racetrack-boat';
export { default as RacetrackCycling } from './icons/racetrack-cycling';
export { default as RacetrackHorse } from './icons/racetrack-horse';
export { default as Racetrack } from './icons/racetrack';
export { default as RailLight } from './icons/rail-light';
export { default as RailMetro } from './icons/rail-metro';
export { default as Rail } from './icons/rail';
export { default as RangerStation } from './icons/ranger-station';
export { default as Recycling } from './icons/recycling';
export { default as ReligiousBuddhist } from './icons/religious-buddhist';
export { default as ReligiousChristian } from './icons/religious-christian';
export { default as ReligiousJewish } from './icons/religious-jewish';
export { default as ReligiousMuslim } from './icons/religious-muslim';
export { default as ReligiousShinto } from './icons/religious-shinto';
export { default as ResidentialCommunity } from './icons/residential-community';
export { default as RestaurantBbq } from './icons/restaurant-bbq';
export { default as RestaurantNoodle } from './icons/restaurant-noodle';
export { default as RestaurantPizza } from './icons/restaurant-pizza';
export { default as RestaurantSeafood } from './icons/restaurant-seafood';
export { default as RestaurantSushi } from './icons/restaurant-sushi';
export { default as Restaurant } from './icons/restaurant';
export { default as RoadAccident } from './icons/road-accident';
export { default as Roadblock } from './icons/roadblock';
export { default as Rocket } from './icons/rocket';
export { default as SchoolJp } from './icons/school-JP';
export { default as School } from './icons/school';
export { default as Scooter } from './icons/scooter';
export { default as Shelter } from './icons/shelter';
export { default as Shoe } from './icons/shoe';
export { default as Shop } from './icons/shop';
export { default as Skateboard } from './icons/skateboard';
export { default as Skiing } from './icons/skiing';
export { default as Slaughterhouse } from './icons/slaughterhouse';
export { default as Slipway } from './icons/slipway';
export { default as Snowmobile } from './icons/snowmobile';
export { default as Soccer } from './icons/soccer';
export { default as SquareStroked } from './icons/square-stroked';
export { default as Square } from './icons/square';
export { default as Stadium } from './icons/stadium';
export { default as StarStroked } from './icons/star-stroked';
export { default as Star } from './icons/star';
export { default as Suitcase } from './icons/suitcase';
export { default as Swimming } from './icons/swimming';
export { default as TableTennis } from './icons/table-tennis';
export { default as Teahouse } from './icons/teahouse';
export { default as Telephone } from './icons/telephone';
export { default as Tennis } from './icons/tennis';
export { default as Theatre } from './icons/theatre';
export { default as Toilet } from './icons/toilet';
export { default as TownHall } from './icons/town-hall';
export { default as Town } from './icons/town';
export { default as TriangleStroked } from './icons/triangle-stroked';
export { default as Triangle } from './icons/triangle';
export { default as Veterinary } from './icons/veterinary';
export { default as Viewpoint } from './icons/viewpoint';
export { default as Village } from './icons/village';
export { default as Volcano } from './icons/volcano';
export { default as Volleyball } from './icons/volleyball';
export { default as Warehouse } from './icons/warehouse';
export { default as WasteBasket } from './icons/waste-basket';
export { default as Watch } from './icons/watch';
export { default as Water } from './icons/water';
export { default as Waterfall } from './icons/waterfall';
export { default as Watermill } from './icons/watermill';
export { default as Wetland } from './icons/wetland';
export { default as Wheelchair } from './icons/wheelchair';
export { default as Windmill } from './icons/windmill';
export { default as Zoo } from './icons/zoo';
type PathsMap = {
  [key:string]: {
    paths: string[]
  }
}
const paths:PathsMap = {};
paths['aerialway'] = { paths: pathsAerialway };
paths['airfield'] = { paths: pathsAirfield };
paths['airport'] = { paths: pathsAirport };
paths['alcohol-shop'] = { paths: pathsAlcoholShop };
paths['american-football'] = { paths: pathsAmericanFootball };
paths['amusement-park'] = { paths: pathsAmusementPark };
paths['aquarium'] = { paths: pathsAquarium };
paths['arrow'] = { paths: pathsArrow };
paths['art-gallery'] = { paths: pathsArtGallery };
paths['attraction'] = { paths: pathsAttraction };
paths['bakery'] = { paths: pathsBakery };
paths['bank-JP'] = { paths: pathsBankJp };
paths['bank'] = { paths: pathsBank };
paths['bar'] = { paths: pathsBar };
paths['barrier'] = { paths: pathsBarrier };
paths['baseball'] = { paths: pathsBaseball };
paths['basketball'] = { paths: pathsBasketball };
paths['bbq'] = { paths: pathsBbq };
paths['beach'] = { paths: pathsBeach };
paths['beer'] = { paths: pathsBeer };
paths['bicycle-share'] = { paths: pathsBicycleShare };
paths['bicycle'] = { paths: pathsBicycle };
paths['blood-bank'] = { paths: pathsBloodBank };
paths['bowling-alley'] = { paths: pathsBowlingAlley };
paths['bridge'] = { paths: pathsBridge };
paths['building-alt1'] = { paths: pathsBuildingAlt1 };
paths['building'] = { paths: pathsBuilding };
paths['bus'] = { paths: pathsBus };
paths['cafe'] = { paths: pathsCafe };
paths['campsite'] = { paths: pathsCampsite };
paths['car-rental'] = { paths: pathsCarRental };
paths['car-repair'] = { paths: pathsCarRepair };
paths['car'] = { paths: pathsCar };
paths['casino'] = { paths: pathsCasino };
paths['castle-JP'] = { paths: pathsCastleJp };
paths['castle'] = { paths: pathsCastle };
paths['caution'] = { paths: pathsCaution };
paths['cemetery-JP'] = { paths: pathsCemeteryJp };
paths['cemetery'] = { paths: pathsCemetery };
paths['charging-station'] = { paths: pathsChargingStation };
paths['cinema'] = { paths: pathsCinema };
paths['circle-stroked'] = { paths: pathsCircleStroked };
paths['circle'] = { paths: pathsCircle };
paths['city'] = { paths: pathsCity };
paths['clothing-store'] = { paths: pathsClothingStore };
paths['college-JP'] = { paths: pathsCollegeJp };
paths['college'] = { paths: pathsCollege };
paths['commercial'] = { paths: pathsCommercial };
paths['communications-tower'] = { paths: pathsCommunicationsTower };
paths['confectionery'] = { paths: pathsConfectionery };
paths['construction'] = { paths: pathsConstruction };
paths['convenience'] = { paths: pathsConvenience };
paths['cricket'] = { paths: pathsCricket };
paths['cross'] = { paths: pathsCross };
paths['dam'] = { paths: pathsDam };
paths['danger'] = { paths: pathsDanger };
paths['defibrillator'] = { paths: pathsDefibrillator };
paths['dentist'] = { paths: pathsDentist };
paths['diamond'] = { paths: pathsDiamond };
paths['doctor'] = { paths: pathsDoctor };
paths['dog-park'] = { paths: pathsDogPark };
paths['drinking-water'] = { paths: pathsDrinkingWater };
paths['elevator'] = { paths: pathsElevator };
paths['embassy'] = { paths: pathsEmbassy };
paths['emergency-phone'] = { paths: pathsEmergencyPhone };
paths['entrance-alt1'] = { paths: pathsEntranceAlt1 };
paths['entrance'] = { paths: pathsEntrance };
paths['farm'] = { paths: pathsFarm };
paths['fast-food'] = { paths: pathsFastFood };
paths['fence'] = { paths: pathsFence };
paths['ferry-JP'] = { paths: pathsFerryJp };
paths['ferry'] = { paths: pathsFerry };
paths['fire-station-JP'] = { paths: pathsFireStationJp };
paths['fire-station'] = { paths: pathsFireStation };
paths['fitness-centre'] = { paths: pathsFitnessCentre };
paths['florist'] = { paths: pathsFlorist };
paths['fuel'] = { paths: pathsFuel };
paths['furniture'] = { paths: pathsFurniture };
paths['gaming'] = { paths: pathsGaming };
paths['garden-centre'] = { paths: pathsGardenCentre };
paths['garden'] = { paths: pathsGarden };
paths['gift'] = { paths: pathsGift };
paths['globe'] = { paths: pathsGlobe };
paths['golf'] = { paths: pathsGolf };
paths['grocery'] = { paths: pathsGrocery };
paths['hairdresser'] = { paths: pathsHairdresser };
paths['harbor'] = { paths: pathsHarbor };
paths['hardware'] = { paths: pathsHardware };
paths['heart'] = { paths: pathsHeart };
paths['heliport'] = { paths: pathsHeliport };
paths['highway-rest-area'] = { paths: pathsHighwayRestArea };
paths['home'] = { paths: pathsHome };
paths['horse-riding'] = { paths: pathsHorseRiding };
paths['hospital-JP'] = { paths: pathsHospitalJp };
paths['hospital'] = { paths: pathsHospital };
paths['hot-spring'] = { paths: pathsHotSpring };
paths['ice-cream'] = { paths: pathsIceCream };
paths['industry'] = { paths: pathsIndustry };
paths['information'] = { paths: pathsInformation };
paths['jewelry-store'] = { paths: pathsJewelryStore };
paths['karaoke'] = { paths: pathsKaraoke };
paths['landmark-JP'] = { paths: pathsLandmarkJp };
paths['landmark'] = { paths: pathsLandmark };
paths['landuse'] = { paths: pathsLanduse };
paths['laundry'] = { paths: pathsLaundry };
paths['library'] = { paths: pathsLibrary };
paths['lighthouse-JP'] = { paths: pathsLighthouseJp };
paths['lighthouse'] = { paths: pathsLighthouse };
paths['lodging'] = { paths: pathsLodging };
paths['logging'] = { paths: pathsLogging };
paths['marker-stroked'] = { paths: pathsMarkerStroked };
paths['marker'] = { paths: pathsMarker };
paths['mobile-phone'] = { paths: pathsMobilePhone };
paths['monument-JP'] = { paths: pathsMonumentJp };
paths['monument'] = { paths: pathsMonument };
paths['mountain'] = { paths: pathsMountain };
paths['museum'] = { paths: pathsMuseum };
paths['music'] = { paths: pathsMusic };
paths['natural'] = { paths: pathsNatural };
paths['observation-tower'] = { paths: pathsObservationTower };
paths['optician'] = { paths: pathsOptician };
paths['paint'] = { paths: pathsPaint };
paths['park-alt1'] = { paths: pathsParkAlt1 };
paths['park'] = { paths: pathsPark };
paths['parking-garage'] = { paths: pathsParkingGarage };
paths['parking'] = { paths: pathsParking };
paths['pharmacy'] = { paths: pathsPharmacy };
paths['picnic-site'] = { paths: pathsPicnicSite };
paths['pitch'] = { paths: pathsPitch };
paths['place-of-worship'] = { paths: pathsPlaceOfWorship };
paths['playground'] = { paths: pathsPlayground };
paths['police-JP'] = { paths: pathsPoliceJp };
paths['police'] = { paths: pathsPolice };
paths['post-JP'] = { paths: pathsPostJp };
paths['post'] = { paths: pathsPost };
paths['prison'] = { paths: pathsPrison };
paths['racetrack-boat'] = { paths: pathsRacetrackBoat };
paths['racetrack-cycling'] = { paths: pathsRacetrackCycling };
paths['racetrack-horse'] = { paths: pathsRacetrackHorse };
paths['racetrack'] = { paths: pathsRacetrack };
paths['rail-light'] = { paths: pathsRailLight };
paths['rail-metro'] = { paths: pathsRailMetro };
paths['rail'] = { paths: pathsRail };
paths['ranger-station'] = { paths: pathsRangerStation };
paths['recycling'] = { paths: pathsRecycling };
paths['religious-buddhist'] = { paths: pathsReligiousBuddhist };
paths['religious-christian'] = { paths: pathsReligiousChristian };
paths['religious-jewish'] = { paths: pathsReligiousJewish };
paths['religious-muslim'] = { paths: pathsReligiousMuslim };
paths['religious-shinto'] = { paths: pathsReligiousShinto };
paths['residential-community'] = { paths: pathsResidentialCommunity };
paths['restaurant-bbq'] = { paths: pathsRestaurantBbq };
paths['restaurant-noodle'] = { paths: pathsRestaurantNoodle };
paths['restaurant-pizza'] = { paths: pathsRestaurantPizza };
paths['restaurant-seafood'] = { paths: pathsRestaurantSeafood };
paths['restaurant-sushi'] = { paths: pathsRestaurantSushi };
paths['restaurant'] = { paths: pathsRestaurant };
paths['road-accident'] = { paths: pathsRoadAccident };
paths['roadblock'] = { paths: pathsRoadblock };
paths['rocket'] = { paths: pathsRocket };
paths['school-JP'] = { paths: pathsSchoolJp };
paths['school'] = { paths: pathsSchool };
paths['scooter'] = { paths: pathsScooter };
paths['shelter'] = { paths: pathsShelter };
paths['shoe'] = { paths: pathsShoe };
paths['shop'] = { paths: pathsShop };
paths['skateboard'] = { paths: pathsSkateboard };
paths['skiing'] = { paths: pathsSkiing };
paths['slaughterhouse'] = { paths: pathsSlaughterhouse };
paths['slipway'] = { paths: pathsSlipway };
paths['snowmobile'] = { paths: pathsSnowmobile };
paths['soccer'] = { paths: pathsSoccer };
paths['square-stroked'] = { paths: pathsSquareStroked };
paths['square'] = { paths: pathsSquare };
paths['stadium'] = { paths: pathsStadium };
paths['star-stroked'] = { paths: pathsStarStroked };
paths['star'] = { paths: pathsStar };
paths['suitcase'] = { paths: pathsSuitcase };
paths['swimming'] = { paths: pathsSwimming };
paths['table-tennis'] = { paths: pathsTableTennis };
paths['teahouse'] = { paths: pathsTeahouse };
paths['telephone'] = { paths: pathsTelephone };
paths['tennis'] = { paths: pathsTennis };
paths['theatre'] = { paths: pathsTheatre };
paths['toilet'] = { paths: pathsToilet };
paths['town-hall'] = { paths: pathsTownHall };
paths['town'] = { paths: pathsTown };
paths['triangle-stroked'] = { paths: pathsTriangleStroked };
paths['triangle'] = { paths: pathsTriangle };
paths['veterinary'] = { paths: pathsVeterinary };
paths['viewpoint'] = { paths: pathsViewpoint };
paths['village'] = { paths: pathsVillage };
paths['volcano'] = { paths: pathsVolcano };
paths['volleyball'] = { paths: pathsVolleyball };
paths['warehouse'] = { paths: pathsWarehouse };
paths['waste-basket'] = { paths: pathsWasteBasket };
paths['watch'] = { paths: pathsWatch };
paths['water'] = { paths: pathsWater };
paths['waterfall'] = { paths: pathsWaterfall };
paths['watermill'] = { paths: pathsWatermill };
paths['wetland'] = { paths: pathsWetland };
paths['wheelchair'] = { paths: pathsWheelchair };
paths['windmill'] = { paths: pathsWindmill };
paths['zoo'] = { paths: pathsZoo };
export const iconsMap = paths;
