
export { default as Aerialway11 } from './icons/aerialway-11';
import { paths as pathsAerialway11 } from './icons/aerialway-11';
export { default as Aerialway15 } from './icons/aerialway-15';
import { paths as pathsAerialway15 } from './icons/aerialway-15';
export { default as Airfield11 } from './icons/airfield-11';
import { paths as pathsAirfield11 } from './icons/airfield-11';
export { default as Airfield15 } from './icons/airfield-15';
import { paths as pathsAirfield15 } from './icons/airfield-15';
export { default as Airport11 } from './icons/airport-11';
import { paths as pathsAirport11 } from './icons/airport-11';
export { default as Airport15 } from './icons/airport-15';
import { paths as pathsAirport15 } from './icons/airport-15';
export { default as AlcoholShop11 } from './icons/alcohol-shop-11';
import { paths as pathsAlcoholShop11 } from './icons/alcohol-shop-11';
export { default as AlcoholShop15 } from './icons/alcohol-shop-15';
import { paths as pathsAlcoholShop15 } from './icons/alcohol-shop-15';
export { default as AmericanFootball11 } from './icons/american-football-11';
import { paths as pathsAmericanFootball11 } from './icons/american-football-11';
export { default as AmericanFootball15 } from './icons/american-football-15';
import { paths as pathsAmericanFootball15 } from './icons/american-football-15';
export { default as AmusementPark11 } from './icons/amusement-park-11';
import { paths as pathsAmusementPark11 } from './icons/amusement-park-11';
export { default as AmusementPark15 } from './icons/amusement-park-15';
import { paths as pathsAmusementPark15 } from './icons/amusement-park-15';
export { default as Aquarium11 } from './icons/aquarium-11';
import { paths as pathsAquarium11 } from './icons/aquarium-11';
export { default as Aquarium15 } from './icons/aquarium-15';
import { paths as pathsAquarium15 } from './icons/aquarium-15';
export { default as ArtGallery11 } from './icons/art-gallery-11';
import { paths as pathsArtGallery11 } from './icons/art-gallery-11';
export { default as ArtGallery15 } from './icons/art-gallery-15';
import { paths as pathsArtGallery15 } from './icons/art-gallery-15';
export { default as Attraction11 } from './icons/attraction-11';
import { paths as pathsAttraction11 } from './icons/attraction-11';
export { default as Attraction15 } from './icons/attraction-15';
import { paths as pathsAttraction15 } from './icons/attraction-15';
export { default as Bakery11 } from './icons/bakery-11';
import { paths as pathsBakery11 } from './icons/bakery-11';
export { default as Bakery15 } from './icons/bakery-15';
import { paths as pathsBakery15 } from './icons/bakery-15';
export { default as Bank11 } from './icons/bank-11';
import { paths as pathsBank11 } from './icons/bank-11';
export { default as Bank15 } from './icons/bank-15';
import { paths as pathsBank15 } from './icons/bank-15';
export { default as BankJp11 } from './icons/bank-JP-11';
import { paths as pathsBankJp11 } from './icons/bank-JP-11';
export { default as BankJp15 } from './icons/bank-JP-15';
import { paths as pathsBankJp15 } from './icons/bank-JP-15';
export { default as Bar11 } from './icons/bar-11';
import { paths as pathsBar11 } from './icons/bar-11';
export { default as Bar15 } from './icons/bar-15';
import { paths as pathsBar15 } from './icons/bar-15';
export { default as Barrier11 } from './icons/barrier-11';
import { paths as pathsBarrier11 } from './icons/barrier-11';
export { default as Barrier15 } from './icons/barrier-15';
import { paths as pathsBarrier15 } from './icons/barrier-15';
export { default as Baseball11 } from './icons/baseball-11';
import { paths as pathsBaseball11 } from './icons/baseball-11';
export { default as Baseball15 } from './icons/baseball-15';
import { paths as pathsBaseball15 } from './icons/baseball-15';
export { default as Basketball11 } from './icons/basketball-11';
import { paths as pathsBasketball11 } from './icons/basketball-11';
export { default as Basketball15 } from './icons/basketball-15';
import { paths as pathsBasketball15 } from './icons/basketball-15';
export { default as Bbq11 } from './icons/bbq-11';
import { paths as pathsBbq11 } from './icons/bbq-11';
export { default as Bbq15 } from './icons/bbq-15';
import { paths as pathsBbq15 } from './icons/bbq-15';
export { default as Beach11 } from './icons/beach-11';
import { paths as pathsBeach11 } from './icons/beach-11';
export { default as Beach15 } from './icons/beach-15';
import { paths as pathsBeach15 } from './icons/beach-15';
export { default as Beer11 } from './icons/beer-11';
import { paths as pathsBeer11 } from './icons/beer-11';
export { default as Beer15 } from './icons/beer-15';
import { paths as pathsBeer15 } from './icons/beer-15';
export { default as Bicycle11 } from './icons/bicycle-11';
import { paths as pathsBicycle11 } from './icons/bicycle-11';
export { default as Bicycle15 } from './icons/bicycle-15';
import { paths as pathsBicycle15 } from './icons/bicycle-15';
export { default as BicycleShare11 } from './icons/bicycle-share-11';
import { paths as pathsBicycleShare11 } from './icons/bicycle-share-11';
export { default as BicycleShare15 } from './icons/bicycle-share-15';
import { paths as pathsBicycleShare15 } from './icons/bicycle-share-15';
export { default as BloodBank11 } from './icons/blood-bank-11';
import { paths as pathsBloodBank11 } from './icons/blood-bank-11';
export { default as BloodBank15 } from './icons/blood-bank-15';
import { paths as pathsBloodBank15 } from './icons/blood-bank-15';
export { default as BowlingAlley11 } from './icons/bowling-alley-11';
import { paths as pathsBowlingAlley11 } from './icons/bowling-alley-11';
export { default as BowlingAlley15 } from './icons/bowling-alley-15';
import { paths as pathsBowlingAlley15 } from './icons/bowling-alley-15';
export { default as Bridge11 } from './icons/bridge-11';
import { paths as pathsBridge11 } from './icons/bridge-11';
export { default as Bridge15 } from './icons/bridge-15';
import { paths as pathsBridge15 } from './icons/bridge-15';
export { default as Building11 } from './icons/building-11';
import { paths as pathsBuilding11 } from './icons/building-11';
export { default as Building15 } from './icons/building-15';
import { paths as pathsBuilding15 } from './icons/building-15';
export { default as BuildingAlt111 } from './icons/building-alt1-11';
import { paths as pathsBuildingAlt111 } from './icons/building-alt1-11';
export { default as BuildingAlt115 } from './icons/building-alt1-15';
import { paths as pathsBuildingAlt115 } from './icons/building-alt1-15';
export { default as Bus11 } from './icons/bus-11';
import { paths as pathsBus11 } from './icons/bus-11';
export { default as Bus15 } from './icons/bus-15';
import { paths as pathsBus15 } from './icons/bus-15';
export { default as Cafe11 } from './icons/cafe-11';
import { paths as pathsCafe11 } from './icons/cafe-11';
export { default as Cafe15 } from './icons/cafe-15';
import { paths as pathsCafe15 } from './icons/cafe-15';
export { default as Campsite11 } from './icons/campsite-11';
import { paths as pathsCampsite11 } from './icons/campsite-11';
export { default as Campsite15 } from './icons/campsite-15';
import { paths as pathsCampsite15 } from './icons/campsite-15';
export { default as Car11 } from './icons/car-11';
import { paths as pathsCar11 } from './icons/car-11';
export { default as Car15 } from './icons/car-15';
import { paths as pathsCar15 } from './icons/car-15';
export { default as CarRental11 } from './icons/car-rental-11';
import { paths as pathsCarRental11 } from './icons/car-rental-11';
export { default as CarRental15 } from './icons/car-rental-15';
import { paths as pathsCarRental15 } from './icons/car-rental-15';
export { default as CarRepair11 } from './icons/car-repair-11';
import { paths as pathsCarRepair11 } from './icons/car-repair-11';
export { default as CarRepair15 } from './icons/car-repair-15';
import { paths as pathsCarRepair15 } from './icons/car-repair-15';
export { default as Casino11 } from './icons/casino-11';
import { paths as pathsCasino11 } from './icons/casino-11';
export { default as Casino15 } from './icons/casino-15';
import { paths as pathsCasino15 } from './icons/casino-15';
export { default as Castle11 } from './icons/castle-11';
import { paths as pathsCastle11 } from './icons/castle-11';
export { default as Castle15 } from './icons/castle-15';
import { paths as pathsCastle15 } from './icons/castle-15';
export { default as CastleJp11 } from './icons/castle-JP-11';
import { paths as pathsCastleJp11 } from './icons/castle-JP-11';
export { default as CastleJp15 } from './icons/castle-JP-15';
import { paths as pathsCastleJp15 } from './icons/castle-JP-15';
export { default as Cemetery11 } from './icons/cemetery-11';
import { paths as pathsCemetery11 } from './icons/cemetery-11';
export { default as Cemetery15 } from './icons/cemetery-15';
import { paths as pathsCemetery15 } from './icons/cemetery-15';
export { default as CemeteryJp11 } from './icons/cemetery-JP-11';
import { paths as pathsCemeteryJp11 } from './icons/cemetery-JP-11';
export { default as CemeteryJp15 } from './icons/cemetery-JP-15';
import { paths as pathsCemeteryJp15 } from './icons/cemetery-JP-15';
export { default as ChargingStation11 } from './icons/charging-station-11';
import { paths as pathsChargingStation11 } from './icons/charging-station-11';
export { default as ChargingStation15 } from './icons/charging-station-15';
import { paths as pathsChargingStation15 } from './icons/charging-station-15';
export { default as Cinema11 } from './icons/cinema-11';
import { paths as pathsCinema11 } from './icons/cinema-11';
export { default as Cinema15 } from './icons/cinema-15';
import { paths as pathsCinema15 } from './icons/cinema-15';
export { default as Circle11 } from './icons/circle-11';
import { paths as pathsCircle11 } from './icons/circle-11';
export { default as Circle15 } from './icons/circle-15';
import { paths as pathsCircle15 } from './icons/circle-15';
export { default as CircleStroked11 } from './icons/circle-stroked-11';
import { paths as pathsCircleStroked11 } from './icons/circle-stroked-11';
export { default as CircleStroked15 } from './icons/circle-stroked-15';
import { paths as pathsCircleStroked15 } from './icons/circle-stroked-15';
export { default as City11 } from './icons/city-11';
import { paths as pathsCity11 } from './icons/city-11';
export { default as City15 } from './icons/city-15';
import { paths as pathsCity15 } from './icons/city-15';
export { default as ClothingStore11 } from './icons/clothing-store-11';
import { paths as pathsClothingStore11 } from './icons/clothing-store-11';
export { default as ClothingStore15 } from './icons/clothing-store-15';
import { paths as pathsClothingStore15 } from './icons/clothing-store-15';
export { default as College11 } from './icons/college-11';
import { paths as pathsCollege11 } from './icons/college-11';
export { default as College15 } from './icons/college-15';
import { paths as pathsCollege15 } from './icons/college-15';
export { default as CollegeJp11 } from './icons/college-JP-11';
import { paths as pathsCollegeJp11 } from './icons/college-JP-11';
export { default as CollegeJp15 } from './icons/college-JP-15';
import { paths as pathsCollegeJp15 } from './icons/college-JP-15';
export { default as Commercial11 } from './icons/commercial-11';
import { paths as pathsCommercial11 } from './icons/commercial-11';
export { default as Commercial15 } from './icons/commercial-15';
import { paths as pathsCommercial15 } from './icons/commercial-15';
export { default as CommunicationsTower11 } from './icons/communications-tower-11';
import { paths as pathsCommunicationsTower11 } from './icons/communications-tower-11';
export { default as CommunicationsTower15 } from './icons/communications-tower-15';
import { paths as pathsCommunicationsTower15 } from './icons/communications-tower-15';
export { default as Confectionery11 } from './icons/confectionery-11';
import { paths as pathsConfectionery11 } from './icons/confectionery-11';
export { default as Confectionery15 } from './icons/confectionery-15';
import { paths as pathsConfectionery15 } from './icons/confectionery-15';
export { default as Convenience11 } from './icons/convenience-11';
import { paths as pathsConvenience11 } from './icons/convenience-11';
export { default as Convenience15 } from './icons/convenience-15';
import { paths as pathsConvenience15 } from './icons/convenience-15';
export { default as Cricket11 } from './icons/cricket-11';
import { paths as pathsCricket11 } from './icons/cricket-11';
export { default as Cricket15 } from './icons/cricket-15';
import { paths as pathsCricket15 } from './icons/cricket-15';
export { default as Cross11 } from './icons/cross-11';
import { paths as pathsCross11 } from './icons/cross-11';
export { default as Cross15 } from './icons/cross-15';
import { paths as pathsCross15 } from './icons/cross-15';
export { default as Dam11 } from './icons/dam-11';
import { paths as pathsDam11 } from './icons/dam-11';
export { default as Dam15 } from './icons/dam-15';
import { paths as pathsDam15 } from './icons/dam-15';
export { default as Danger11 } from './icons/danger-11';
import { paths as pathsDanger11 } from './icons/danger-11';
export { default as Danger15 } from './icons/danger-15';
import { paths as pathsDanger15 } from './icons/danger-15';
export { default as Defibrillator11 } from './icons/defibrillator-11';
import { paths as pathsDefibrillator11 } from './icons/defibrillator-11';
export { default as Defibrillator15 } from './icons/defibrillator-15';
import { paths as pathsDefibrillator15 } from './icons/defibrillator-15';
export { default as Dentist11 } from './icons/dentist-11';
import { paths as pathsDentist11 } from './icons/dentist-11';
export { default as Dentist15 } from './icons/dentist-15';
import { paths as pathsDentist15 } from './icons/dentist-15';
export { default as Doctor11 } from './icons/doctor-11';
import { paths as pathsDoctor11 } from './icons/doctor-11';
export { default as Doctor15 } from './icons/doctor-15';
import { paths as pathsDoctor15 } from './icons/doctor-15';
export { default as DogPark11 } from './icons/dog-park-11';
import { paths as pathsDogPark11 } from './icons/dog-park-11';
export { default as DogPark15 } from './icons/dog-park-15';
import { paths as pathsDogPark15 } from './icons/dog-park-15';
export { default as DrinkingWater11 } from './icons/drinking-water-11';
import { paths as pathsDrinkingWater11 } from './icons/drinking-water-11';
export { default as DrinkingWater15 } from './icons/drinking-water-15';
import { paths as pathsDrinkingWater15 } from './icons/drinking-water-15';
export { default as Embassy11 } from './icons/embassy-11';
import { paths as pathsEmbassy11 } from './icons/embassy-11';
export { default as Embassy15 } from './icons/embassy-15';
import { paths as pathsEmbassy15 } from './icons/embassy-15';
export { default as EmergencyPhone11 } from './icons/emergency-phone-11';
import { paths as pathsEmergencyPhone11 } from './icons/emergency-phone-11';
export { default as EmergencyPhone15 } from './icons/emergency-phone-15';
import { paths as pathsEmergencyPhone15 } from './icons/emergency-phone-15';
export { default as Entrance11 } from './icons/entrance-11';
import { paths as pathsEntrance11 } from './icons/entrance-11';
export { default as Entrance15 } from './icons/entrance-15';
import { paths as pathsEntrance15 } from './icons/entrance-15';
export { default as EntranceAlt111 } from './icons/entrance-alt1-11';
import { paths as pathsEntranceAlt111 } from './icons/entrance-alt1-11';
export { default as EntranceAlt115 } from './icons/entrance-alt1-15';
import { paths as pathsEntranceAlt115 } from './icons/entrance-alt1-15';
export { default as Farm11 } from './icons/farm-11';
import { paths as pathsFarm11 } from './icons/farm-11';
export { default as Farm15 } from './icons/farm-15';
import { paths as pathsFarm15 } from './icons/farm-15';
export { default as FastFood11 } from './icons/fast-food-11';
import { paths as pathsFastFood11 } from './icons/fast-food-11';
export { default as FastFood15 } from './icons/fast-food-15';
import { paths as pathsFastFood15 } from './icons/fast-food-15';
export { default as Fence11 } from './icons/fence-11';
import { paths as pathsFence11 } from './icons/fence-11';
export { default as Fence15 } from './icons/fence-15';
import { paths as pathsFence15 } from './icons/fence-15';
export { default as Ferry11 } from './icons/ferry-11';
import { paths as pathsFerry11 } from './icons/ferry-11';
export { default as Ferry15 } from './icons/ferry-15';
import { paths as pathsFerry15 } from './icons/ferry-15';
export { default as FireStation11 } from './icons/fire-station-11';
import { paths as pathsFireStation11 } from './icons/fire-station-11';
export { default as FireStation15 } from './icons/fire-station-15';
import { paths as pathsFireStation15 } from './icons/fire-station-15';
export { default as FireStationJp11 } from './icons/fire-station-JP-11';
import { paths as pathsFireStationJp11 } from './icons/fire-station-JP-11';
export { default as FireStationJp15 } from './icons/fire-station-JP-15';
import { paths as pathsFireStationJp15 } from './icons/fire-station-JP-15';
export { default as FitnessCentre11 } from './icons/fitness-centre-11';
import { paths as pathsFitnessCentre11 } from './icons/fitness-centre-11';
export { default as FitnessCentre15 } from './icons/fitness-centre-15';
import { paths as pathsFitnessCentre15 } from './icons/fitness-centre-15';
export { default as Florist11 } from './icons/florist-11';
import { paths as pathsFlorist11 } from './icons/florist-11';
export { default as Florist15 } from './icons/florist-15';
import { paths as pathsFlorist15 } from './icons/florist-15';
export { default as Fuel11 } from './icons/fuel-11';
import { paths as pathsFuel11 } from './icons/fuel-11';
export { default as Fuel15 } from './icons/fuel-15';
import { paths as pathsFuel15 } from './icons/fuel-15';
export { default as Furniture11 } from './icons/furniture-11';
import { paths as pathsFurniture11 } from './icons/furniture-11';
export { default as Furniture15 } from './icons/furniture-15';
import { paths as pathsFurniture15 } from './icons/furniture-15';
export { default as Gaming11 } from './icons/gaming-11';
import { paths as pathsGaming11 } from './icons/gaming-11';
export { default as Gaming15 } from './icons/gaming-15';
import { paths as pathsGaming15 } from './icons/gaming-15';
export { default as Garden11 } from './icons/garden-11';
import { paths as pathsGarden11 } from './icons/garden-11';
export { default as Garden15 } from './icons/garden-15';
import { paths as pathsGarden15 } from './icons/garden-15';
export { default as GardenCentre11 } from './icons/garden-centre-11';
import { paths as pathsGardenCentre11 } from './icons/garden-centre-11';
export { default as GardenCentre15 } from './icons/garden-centre-15';
import { paths as pathsGardenCentre15 } from './icons/garden-centre-15';
export { default as Gift11 } from './icons/gift-11';
import { paths as pathsGift11 } from './icons/gift-11';
export { default as Gift15 } from './icons/gift-15';
import { paths as pathsGift15 } from './icons/gift-15';
export { default as Globe11 } from './icons/globe-11';
import { paths as pathsGlobe11 } from './icons/globe-11';
export { default as Globe15 } from './icons/globe-15';
import { paths as pathsGlobe15 } from './icons/globe-15';
export { default as Golf11 } from './icons/golf-11';
import { paths as pathsGolf11 } from './icons/golf-11';
export { default as Golf15 } from './icons/golf-15';
import { paths as pathsGolf15 } from './icons/golf-15';
export { default as Grocery11 } from './icons/grocery-11';
import { paths as pathsGrocery11 } from './icons/grocery-11';
export { default as Grocery15 } from './icons/grocery-15';
import { paths as pathsGrocery15 } from './icons/grocery-15';
export { default as Hairdresser11 } from './icons/hairdresser-11';
import { paths as pathsHairdresser11 } from './icons/hairdresser-11';
export { default as Hairdresser15 } from './icons/hairdresser-15';
import { paths as pathsHairdresser15 } from './icons/hairdresser-15';
export { default as Harbor11 } from './icons/harbor-11';
import { paths as pathsHarbor11 } from './icons/harbor-11';
export { default as Harbor15 } from './icons/harbor-15';
import { paths as pathsHarbor15 } from './icons/harbor-15';
export { default as Hardware11 } from './icons/hardware-11';
import { paths as pathsHardware11 } from './icons/hardware-11';
export { default as Hardware15 } from './icons/hardware-15';
import { paths as pathsHardware15 } from './icons/hardware-15';
export { default as Heart11 } from './icons/heart-11';
import { paths as pathsHeart11 } from './icons/heart-11';
export { default as Heart15 } from './icons/heart-15';
import { paths as pathsHeart15 } from './icons/heart-15';
export { default as Heliport11 } from './icons/heliport-11';
import { paths as pathsHeliport11 } from './icons/heliport-11';
export { default as Heliport15 } from './icons/heliport-15';
import { paths as pathsHeliport15 } from './icons/heliport-15';
export { default as Home11 } from './icons/home-11';
import { paths as pathsHome11 } from './icons/home-11';
export { default as Home15 } from './icons/home-15';
import { paths as pathsHome15 } from './icons/home-15';
export { default as HorseRiding11 } from './icons/horse-riding-11';
import { paths as pathsHorseRiding11 } from './icons/horse-riding-11';
export { default as HorseRiding15 } from './icons/horse-riding-15';
import { paths as pathsHorseRiding15 } from './icons/horse-riding-15';
export { default as Hospital11 } from './icons/hospital-11';
import { paths as pathsHospital11 } from './icons/hospital-11';
export { default as Hospital15 } from './icons/hospital-15';
import { paths as pathsHospital15 } from './icons/hospital-15';
export { default as HospitalJp11 } from './icons/hospital-JP-11';
import { paths as pathsHospitalJp11 } from './icons/hospital-JP-11';
export { default as HospitalJp15 } from './icons/hospital-JP-15';
import { paths as pathsHospitalJp15 } from './icons/hospital-JP-15';
export { default as IceCream11 } from './icons/ice-cream-11';
import { paths as pathsIceCream11 } from './icons/ice-cream-11';
export { default as IceCream15 } from './icons/ice-cream-15';
import { paths as pathsIceCream15 } from './icons/ice-cream-15';
export { default as Industry11 } from './icons/industry-11';
import { paths as pathsIndustry11 } from './icons/industry-11';
export { default as Industry15 } from './icons/industry-15';
import { paths as pathsIndustry15 } from './icons/industry-15';
export { default as Information11 } from './icons/information-11';
import { paths as pathsInformation11 } from './icons/information-11';
export { default as Information15 } from './icons/information-15';
import { paths as pathsInformation15 } from './icons/information-15';
export { default as JewelryStore11 } from './icons/jewelry-store-11';
import { paths as pathsJewelryStore11 } from './icons/jewelry-store-11';
export { default as JewelryStore15 } from './icons/jewelry-store-15';
import { paths as pathsJewelryStore15 } from './icons/jewelry-store-15';
export { default as Karaoke11 } from './icons/karaoke-11';
import { paths as pathsKaraoke11 } from './icons/karaoke-11';
export { default as Karaoke15 } from './icons/karaoke-15';
import { paths as pathsKaraoke15 } from './icons/karaoke-15';
export { default as Landmark11 } from './icons/landmark-11';
import { paths as pathsLandmark11 } from './icons/landmark-11';
export { default as Landmark15 } from './icons/landmark-15';
import { paths as pathsLandmark15 } from './icons/landmark-15';
export { default as LandmarkJp11 } from './icons/landmark-JP-11';
import { paths as pathsLandmarkJp11 } from './icons/landmark-JP-11';
export { default as LandmarkJp15 } from './icons/landmark-JP-15';
import { paths as pathsLandmarkJp15 } from './icons/landmark-JP-15';
export { default as Landuse11 } from './icons/landuse-11';
import { paths as pathsLanduse11 } from './icons/landuse-11';
export { default as Landuse15 } from './icons/landuse-15';
import { paths as pathsLanduse15 } from './icons/landuse-15';
export { default as Laundry11 } from './icons/laundry-11';
import { paths as pathsLaundry11 } from './icons/laundry-11';
export { default as Laundry15 } from './icons/laundry-15';
import { paths as pathsLaundry15 } from './icons/laundry-15';
export { default as Library11 } from './icons/library-11';
import { paths as pathsLibrary11 } from './icons/library-11';
export { default as Library15 } from './icons/library-15';
import { paths as pathsLibrary15 } from './icons/library-15';
export { default as Lighthouse11 } from './icons/lighthouse-11';
import { paths as pathsLighthouse11 } from './icons/lighthouse-11';
export { default as Lighthouse15 } from './icons/lighthouse-15';
import { paths as pathsLighthouse15 } from './icons/lighthouse-15';
export { default as Lodging11 } from './icons/lodging-11';
import { paths as pathsLodging11 } from './icons/lodging-11';
export { default as Lodging15 } from './icons/lodging-15';
import { paths as pathsLodging15 } from './icons/lodging-15';
export { default as Logging11 } from './icons/logging-11';
import { paths as pathsLogging11 } from './icons/logging-11';
export { default as Logging15 } from './icons/logging-15';
import { paths as pathsLogging15 } from './icons/logging-15';
export { default as Marker11 } from './icons/marker-11';
import { paths as pathsMarker11 } from './icons/marker-11';
export { default as Marker15 } from './icons/marker-15';
import { paths as pathsMarker15 } from './icons/marker-15';
export { default as MarkerStroked11 } from './icons/marker-stroked-11';
import { paths as pathsMarkerStroked11 } from './icons/marker-stroked-11';
export { default as MarkerStroked15 } from './icons/marker-stroked-15';
import { paths as pathsMarkerStroked15 } from './icons/marker-stroked-15';
export { default as MobilePhone11 } from './icons/mobile-phone-11';
import { paths as pathsMobilePhone11 } from './icons/mobile-phone-11';
export { default as MobilePhone15 } from './icons/mobile-phone-15';
import { paths as pathsMobilePhone15 } from './icons/mobile-phone-15';
export { default as Monument11 } from './icons/monument-11';
import { paths as pathsMonument11 } from './icons/monument-11';
export { default as Monument15 } from './icons/monument-15';
import { paths as pathsMonument15 } from './icons/monument-15';
export { default as Mountain11 } from './icons/mountain-11';
import { paths as pathsMountain11 } from './icons/mountain-11';
export { default as Mountain15 } from './icons/mountain-15';
import { paths as pathsMountain15 } from './icons/mountain-15';
export { default as Museum11 } from './icons/museum-11';
import { paths as pathsMuseum11 } from './icons/museum-11';
export { default as Museum15 } from './icons/museum-15';
import { paths as pathsMuseum15 } from './icons/museum-15';
export { default as Music11 } from './icons/music-11';
import { paths as pathsMusic11 } from './icons/music-11';
export { default as Music15 } from './icons/music-15';
import { paths as pathsMusic15 } from './icons/music-15';
export { default as Natural11 } from './icons/natural-11';
import { paths as pathsNatural11 } from './icons/natural-11';
export { default as Natural15 } from './icons/natural-15';
import { paths as pathsNatural15 } from './icons/natural-15';
export { default as Optician11 } from './icons/optician-11';
import { paths as pathsOptician11 } from './icons/optician-11';
export { default as Optician15 } from './icons/optician-15';
import { paths as pathsOptician15 } from './icons/optician-15';
export { default as Paint11 } from './icons/paint-11';
import { paths as pathsPaint11 } from './icons/paint-11';
export { default as Paint15 } from './icons/paint-15';
import { paths as pathsPaint15 } from './icons/paint-15';
export { default as Park11 } from './icons/park-11';
import { paths as pathsPark11 } from './icons/park-11';
export { default as Park15 } from './icons/park-15';
import { paths as pathsPark15 } from './icons/park-15';
export { default as ParkAlt111 } from './icons/park-alt1-11';
import { paths as pathsParkAlt111 } from './icons/park-alt1-11';
export { default as ParkAlt115 } from './icons/park-alt1-15';
import { paths as pathsParkAlt115 } from './icons/park-alt1-15';
export { default as Parking11 } from './icons/parking-11';
import { paths as pathsParking11 } from './icons/parking-11';
export { default as Parking15 } from './icons/parking-15';
import { paths as pathsParking15 } from './icons/parking-15';
export { default as ParkingGarage11 } from './icons/parking-garage-11';
import { paths as pathsParkingGarage11 } from './icons/parking-garage-11';
export { default as ParkingGarage15 } from './icons/parking-garage-15';
import { paths as pathsParkingGarage15 } from './icons/parking-garage-15';
export { default as Pharmacy11 } from './icons/pharmacy-11';
import { paths as pathsPharmacy11 } from './icons/pharmacy-11';
export { default as Pharmacy15 } from './icons/pharmacy-15';
import { paths as pathsPharmacy15 } from './icons/pharmacy-15';
export { default as PicnicSite11 } from './icons/picnic-site-11';
import { paths as pathsPicnicSite11 } from './icons/picnic-site-11';
export { default as PicnicSite15 } from './icons/picnic-site-15';
import { paths as pathsPicnicSite15 } from './icons/picnic-site-15';
export { default as Pitch11 } from './icons/pitch-11';
import { paths as pathsPitch11 } from './icons/pitch-11';
export { default as Pitch15 } from './icons/pitch-15';
import { paths as pathsPitch15 } from './icons/pitch-15';
export { default as PlaceOfWorship11 } from './icons/place-of-worship-11';
import { paths as pathsPlaceOfWorship11 } from './icons/place-of-worship-11';
export { default as PlaceOfWorship15 } from './icons/place-of-worship-15';
import { paths as pathsPlaceOfWorship15 } from './icons/place-of-worship-15';
export { default as Playground11 } from './icons/playground-11';
import { paths as pathsPlayground11 } from './icons/playground-11';
export { default as Playground15 } from './icons/playground-15';
import { paths as pathsPlayground15 } from './icons/playground-15';
export { default as Police11 } from './icons/police-11';
import { paths as pathsPolice11 } from './icons/police-11';
export { default as Police15 } from './icons/police-15';
import { paths as pathsPolice15 } from './icons/police-15';
export { default as PoliceJp11 } from './icons/police-JP-11';
import { paths as pathsPoliceJp11 } from './icons/police-JP-11';
export { default as PoliceJp15 } from './icons/police-JP-15';
import { paths as pathsPoliceJp15 } from './icons/police-JP-15';
export { default as Post11 } from './icons/post-11';
import { paths as pathsPost11 } from './icons/post-11';
export { default as Post15 } from './icons/post-15';
import { paths as pathsPost15 } from './icons/post-15';
export { default as PostJp11 } from './icons/post-JP-11';
import { paths as pathsPostJp11 } from './icons/post-JP-11';
export { default as PostJp15 } from './icons/post-JP-15';
import { paths as pathsPostJp15 } from './icons/post-JP-15';
export { default as Prison11 } from './icons/prison-11';
import { paths as pathsPrison11 } from './icons/prison-11';
export { default as Prison15 } from './icons/prison-15';
import { paths as pathsPrison15 } from './icons/prison-15';
export { default as Rail11 } from './icons/rail-11';
import { paths as pathsRail11 } from './icons/rail-11';
export { default as Rail15 } from './icons/rail-15';
import { paths as pathsRail15 } from './icons/rail-15';
export { default as RailLight11 } from './icons/rail-light-11';
import { paths as pathsRailLight11 } from './icons/rail-light-11';
export { default as RailLight15 } from './icons/rail-light-15';
import { paths as pathsRailLight15 } from './icons/rail-light-15';
export { default as RailMetro11 } from './icons/rail-metro-11';
import { paths as pathsRailMetro11 } from './icons/rail-metro-11';
export { default as RailMetro15 } from './icons/rail-metro-15';
import { paths as pathsRailMetro15 } from './icons/rail-metro-15';
export { default as RangerStation11 } from './icons/ranger-station-11';
import { paths as pathsRangerStation11 } from './icons/ranger-station-11';
export { default as RangerStation15 } from './icons/ranger-station-15';
import { paths as pathsRangerStation15 } from './icons/ranger-station-15';
export { default as Recycling11 } from './icons/recycling-11';
import { paths as pathsRecycling11 } from './icons/recycling-11';
export { default as Recycling15 } from './icons/recycling-15';
import { paths as pathsRecycling15 } from './icons/recycling-15';
export { default as ReligiousBuddhist11 } from './icons/religious-buddhist-11';
import { paths as pathsReligiousBuddhist11 } from './icons/religious-buddhist-11';
export { default as ReligiousBuddhist15 } from './icons/religious-buddhist-15';
import { paths as pathsReligiousBuddhist15 } from './icons/religious-buddhist-15';
export { default as ReligiousChristian11 } from './icons/religious-christian-11';
import { paths as pathsReligiousChristian11 } from './icons/religious-christian-11';
export { default as ReligiousChristian15 } from './icons/religious-christian-15';
import { paths as pathsReligiousChristian15 } from './icons/religious-christian-15';
export { default as ReligiousJewish11 } from './icons/religious-jewish-11';
import { paths as pathsReligiousJewish11 } from './icons/religious-jewish-11';
export { default as ReligiousJewish15 } from './icons/religious-jewish-15';
import { paths as pathsReligiousJewish15 } from './icons/religious-jewish-15';
export { default as ReligiousMuslim11 } from './icons/religious-muslim-11';
import { paths as pathsReligiousMuslim11 } from './icons/religious-muslim-11';
export { default as ReligiousMuslim15 } from './icons/religious-muslim-15';
import { paths as pathsReligiousMuslim15 } from './icons/religious-muslim-15';
export { default as ReligiousShinto11 } from './icons/religious-shinto-11';
import { paths as pathsReligiousShinto11 } from './icons/religious-shinto-11';
export { default as ReligiousShinto15 } from './icons/religious-shinto-15';
import { paths as pathsReligiousShinto15 } from './icons/religious-shinto-15';
export { default as ResidentialCommunity11 } from './icons/residential-community-11';
import { paths as pathsResidentialCommunity11 } from './icons/residential-community-11';
export { default as ResidentialCommunity15 } from './icons/residential-community-15';
import { paths as pathsResidentialCommunity15 } from './icons/residential-community-15';
export { default as Restaurant11 } from './icons/restaurant-11';
import { paths as pathsRestaurant11 } from './icons/restaurant-11';
export { default as Restaurant15 } from './icons/restaurant-15';
import { paths as pathsRestaurant15 } from './icons/restaurant-15';
export { default as RestaurantNoodle11 } from './icons/restaurant-noodle-11';
import { paths as pathsRestaurantNoodle11 } from './icons/restaurant-noodle-11';
export { default as RestaurantNoodle15 } from './icons/restaurant-noodle-15';
import { paths as pathsRestaurantNoodle15 } from './icons/restaurant-noodle-15';
export { default as RestaurantPizza11 } from './icons/restaurant-pizza-11';
import { paths as pathsRestaurantPizza11 } from './icons/restaurant-pizza-11';
export { default as RestaurantPizza15 } from './icons/restaurant-pizza-15';
import { paths as pathsRestaurantPizza15 } from './icons/restaurant-pizza-15';
export { default as RestaurantSeafood11 } from './icons/restaurant-seafood-11';
import { paths as pathsRestaurantSeafood11 } from './icons/restaurant-seafood-11';
export { default as RestaurantSeafood15 } from './icons/restaurant-seafood-15';
import { paths as pathsRestaurantSeafood15 } from './icons/restaurant-seafood-15';
export { default as Roadblock11 } from './icons/roadblock-11';
import { paths as pathsRoadblock11 } from './icons/roadblock-11';
export { default as Roadblock15 } from './icons/roadblock-15';
import { paths as pathsRoadblock15 } from './icons/roadblock-15';
export { default as Rocket11 } from './icons/rocket-11';
import { paths as pathsRocket11 } from './icons/rocket-11';
export { default as Rocket15 } from './icons/rocket-15';
import { paths as pathsRocket15 } from './icons/rocket-15';
export { default as School11 } from './icons/school-11';
import { paths as pathsSchool11 } from './icons/school-11';
export { default as School15 } from './icons/school-15';
import { paths as pathsSchool15 } from './icons/school-15';
export { default as SchoolJp11 } from './icons/school-JP-11';
import { paths as pathsSchoolJp11 } from './icons/school-JP-11';
export { default as SchoolJp15 } from './icons/school-JP-15';
import { paths as pathsSchoolJp15 } from './icons/school-JP-15';
export { default as Scooter11 } from './icons/scooter-11';
import { paths as pathsScooter11 } from './icons/scooter-11';
export { default as Scooter15 } from './icons/scooter-15';
import { paths as pathsScooter15 } from './icons/scooter-15';
export { default as Shelter11 } from './icons/shelter-11';
import { paths as pathsShelter11 } from './icons/shelter-11';
export { default as Shelter15 } from './icons/shelter-15';
import { paths as pathsShelter15 } from './icons/shelter-15';
export { default as Shoe11 } from './icons/shoe-11';
import { paths as pathsShoe11 } from './icons/shoe-11';
export { default as Shoe15 } from './icons/shoe-15';
import { paths as pathsShoe15 } from './icons/shoe-15';
export { default as Shop11 } from './icons/shop-11';
import { paths as pathsShop11 } from './icons/shop-11';
export { default as Shop15 } from './icons/shop-15';
import { paths as pathsShop15 } from './icons/shop-15';
export { default as Skateboard11 } from './icons/skateboard-11';
import { paths as pathsSkateboard11 } from './icons/skateboard-11';
export { default as Skateboard15 } from './icons/skateboard-15';
import { paths as pathsSkateboard15 } from './icons/skateboard-15';
export { default as Skiing11 } from './icons/skiing-11';
import { paths as pathsSkiing11 } from './icons/skiing-11';
export { default as Skiing15 } from './icons/skiing-15';
import { paths as pathsSkiing15 } from './icons/skiing-15';
export { default as Slaughterhouse11 } from './icons/slaughterhouse-11';
import { paths as pathsSlaughterhouse11 } from './icons/slaughterhouse-11';
export { default as Slaughterhouse15 } from './icons/slaughterhouse-15';
import { paths as pathsSlaughterhouse15 } from './icons/slaughterhouse-15';
export { default as Slipway11 } from './icons/slipway-11';
import { paths as pathsSlipway11 } from './icons/slipway-11';
export { default as Slipway15 } from './icons/slipway-15';
import { paths as pathsSlipway15 } from './icons/slipway-15';
export { default as Snowmobile11 } from './icons/snowmobile-11';
import { paths as pathsSnowmobile11 } from './icons/snowmobile-11';
export { default as Snowmobile15 } from './icons/snowmobile-15';
import { paths as pathsSnowmobile15 } from './icons/snowmobile-15';
export { default as Soccer11 } from './icons/soccer-11';
import { paths as pathsSoccer11 } from './icons/soccer-11';
export { default as Soccer15 } from './icons/soccer-15';
import { paths as pathsSoccer15 } from './icons/soccer-15';
export { default as Square11 } from './icons/square-11';
import { paths as pathsSquare11 } from './icons/square-11';
export { default as Square15 } from './icons/square-15';
import { paths as pathsSquare15 } from './icons/square-15';
export { default as SquareStroked11 } from './icons/square-stroked-11';
import { paths as pathsSquareStroked11 } from './icons/square-stroked-11';
export { default as SquareStroked15 } from './icons/square-stroked-15';
import { paths as pathsSquareStroked15 } from './icons/square-stroked-15';
export { default as Stadium11 } from './icons/stadium-11';
import { paths as pathsStadium11 } from './icons/stadium-11';
export { default as Stadium15 } from './icons/stadium-15';
import { paths as pathsStadium15 } from './icons/stadium-15';
export { default as Star11 } from './icons/star-11';
import { paths as pathsStar11 } from './icons/star-11';
export { default as Star15 } from './icons/star-15';
import { paths as pathsStar15 } from './icons/star-15';
export { default as StarStroked11 } from './icons/star-stroked-11';
import { paths as pathsStarStroked11 } from './icons/star-stroked-11';
export { default as StarStroked15 } from './icons/star-stroked-15';
import { paths as pathsStarStroked15 } from './icons/star-stroked-15';
export { default as Suitcase11 } from './icons/suitcase-11';
import { paths as pathsSuitcase11 } from './icons/suitcase-11';
export { default as Suitcase15 } from './icons/suitcase-15';
import { paths as pathsSuitcase15 } from './icons/suitcase-15';
export { default as Sushi11 } from './icons/sushi-11';
import { paths as pathsSushi11 } from './icons/sushi-11';
export { default as Sushi15 } from './icons/sushi-15';
import { paths as pathsSushi15 } from './icons/sushi-15';
export { default as Swimming11 } from './icons/swimming-11';
import { paths as pathsSwimming11 } from './icons/swimming-11';
export { default as Swimming15 } from './icons/swimming-15';
import { paths as pathsSwimming15 } from './icons/swimming-15';
export { default as TableTennis11 } from './icons/table-tennis-11';
import { paths as pathsTableTennis11 } from './icons/table-tennis-11';
export { default as TableTennis15 } from './icons/table-tennis-15';
import { paths as pathsTableTennis15 } from './icons/table-tennis-15';
export { default as Teahouse11 } from './icons/teahouse-11';
import { paths as pathsTeahouse11 } from './icons/teahouse-11';
export { default as Teahouse15 } from './icons/teahouse-15';
import { paths as pathsTeahouse15 } from './icons/teahouse-15';
export { default as Telephone11 } from './icons/telephone-11';
import { paths as pathsTelephone11 } from './icons/telephone-11';
export { default as Telephone15 } from './icons/telephone-15';
import { paths as pathsTelephone15 } from './icons/telephone-15';
export { default as Tennis11 } from './icons/tennis-11';
import { paths as pathsTennis11 } from './icons/tennis-11';
export { default as Tennis15 } from './icons/tennis-15';
import { paths as pathsTennis15 } from './icons/tennis-15';
export { default as Theatre11 } from './icons/theatre-11';
import { paths as pathsTheatre11 } from './icons/theatre-11';
export { default as Theatre15 } from './icons/theatre-15';
import { paths as pathsTheatre15 } from './icons/theatre-15';
export { default as Toilet11 } from './icons/toilet-11';
import { paths as pathsToilet11 } from './icons/toilet-11';
export { default as Toilet15 } from './icons/toilet-15';
import { paths as pathsToilet15 } from './icons/toilet-15';
export { default as Town11 } from './icons/town-11';
import { paths as pathsTown11 } from './icons/town-11';
export { default as Town15 } from './icons/town-15';
import { paths as pathsTown15 } from './icons/town-15';
export { default as TownHall11 } from './icons/town-hall-11';
import { paths as pathsTownHall11 } from './icons/town-hall-11';
export { default as TownHall15 } from './icons/town-hall-15';
import { paths as pathsTownHall15 } from './icons/town-hall-15';
export { default as Triangle11 } from './icons/triangle-11';
import { paths as pathsTriangle11 } from './icons/triangle-11';
export { default as Triangle15 } from './icons/triangle-15';
import { paths as pathsTriangle15 } from './icons/triangle-15';
export { default as TriangleStroked11 } from './icons/triangle-stroked-11';
import { paths as pathsTriangleStroked11 } from './icons/triangle-stroked-11';
export { default as TriangleStroked15 } from './icons/triangle-stroked-15';
import { paths as pathsTriangleStroked15 } from './icons/triangle-stroked-15';
export { default as Veterinary11 } from './icons/veterinary-11';
import { paths as pathsVeterinary11 } from './icons/veterinary-11';
export { default as Veterinary15 } from './icons/veterinary-15';
import { paths as pathsVeterinary15 } from './icons/veterinary-15';
export { default as Viewpoint11 } from './icons/viewpoint-11';
import { paths as pathsViewpoint11 } from './icons/viewpoint-11';
export { default as Viewpoint15 } from './icons/viewpoint-15';
import { paths as pathsViewpoint15 } from './icons/viewpoint-15';
export { default as Village11 } from './icons/village-11';
import { paths as pathsVillage11 } from './icons/village-11';
export { default as Village15 } from './icons/village-15';
import { paths as pathsVillage15 } from './icons/village-15';
export { default as Volcano11 } from './icons/volcano-11';
import { paths as pathsVolcano11 } from './icons/volcano-11';
export { default as Volcano15 } from './icons/volcano-15';
import { paths as pathsVolcano15 } from './icons/volcano-15';
export { default as Volleyball11 } from './icons/volleyball-11';
import { paths as pathsVolleyball11 } from './icons/volleyball-11';
export { default as Volleyball15 } from './icons/volleyball-15';
import { paths as pathsVolleyball15 } from './icons/volleyball-15';
export { default as Warehouse11 } from './icons/warehouse-11';
import { paths as pathsWarehouse11 } from './icons/warehouse-11';
export { default as Warehouse15 } from './icons/warehouse-15';
import { paths as pathsWarehouse15 } from './icons/warehouse-15';
export { default as WasteBasket11 } from './icons/waste-basket-11';
import { paths as pathsWasteBasket11 } from './icons/waste-basket-11';
export { default as WasteBasket15 } from './icons/waste-basket-15';
import { paths as pathsWasteBasket15 } from './icons/waste-basket-15';
export { default as Watch11 } from './icons/watch-11';
import { paths as pathsWatch11 } from './icons/watch-11';
export { default as Watch15 } from './icons/watch-15';
import { paths as pathsWatch15 } from './icons/watch-15';
export { default as Water11 } from './icons/water-11';
import { paths as pathsWater11 } from './icons/water-11';
export { default as Water15 } from './icons/water-15';
import { paths as pathsWater15 } from './icons/water-15';
export { default as Waterfall11 } from './icons/waterfall-11';
import { paths as pathsWaterfall11 } from './icons/waterfall-11';
export { default as Waterfall15 } from './icons/waterfall-15';
import { paths as pathsWaterfall15 } from './icons/waterfall-15';
export { default as Watermill11 } from './icons/watermill-11';
import { paths as pathsWatermill11 } from './icons/watermill-11';
export { default as Watermill15 } from './icons/watermill-15';
import { paths as pathsWatermill15 } from './icons/watermill-15';
export { default as Wetland11 } from './icons/wetland-11';
import { paths as pathsWetland11 } from './icons/wetland-11';
export { default as Wetland15 } from './icons/wetland-15';
import { paths as pathsWetland15 } from './icons/wetland-15';
export { default as Wheelchair11 } from './icons/wheelchair-11';
import { paths as pathsWheelchair11 } from './icons/wheelchair-11';
export { default as Wheelchair15 } from './icons/wheelchair-15';
import { paths as pathsWheelchair15 } from './icons/wheelchair-15';
export { default as Windmill11 } from './icons/windmill-11';
import { paths as pathsWindmill11 } from './icons/windmill-11';
export { default as Windmill15 } from './icons/windmill-15';
import { paths as pathsWindmill15 } from './icons/windmill-15';
export { default as Zoo11 } from './icons/zoo-11';
import { paths as pathsZoo11 } from './icons/zoo-11';
export { default as Zoo15 } from './icons/zoo-15';
import { paths as pathsZoo15 } from './icons/zoo-15';
type PathsMap = {
  [key:string]: {
    paths: string[]
  }
}
const paths:PathsMap = {};
paths['aerialway-11'] = { paths: pathsAerialway11 };
paths['aerialway-15'] = { paths: pathsAerialway15 };
paths['airfield-11'] = { paths: pathsAirfield11 };
paths['airfield-15'] = { paths: pathsAirfield15 };
paths['airport-11'] = { paths: pathsAirport11 };
paths['airport-15'] = { paths: pathsAirport15 };
paths['alcohol-shop-11'] = { paths: pathsAlcoholShop11 };
paths['alcohol-shop-15'] = { paths: pathsAlcoholShop15 };
paths['american-football-11'] = { paths: pathsAmericanFootball11 };
paths['american-football-15'] = { paths: pathsAmericanFootball15 };
paths['amusement-park-11'] = { paths: pathsAmusementPark11 };
paths['amusement-park-15'] = { paths: pathsAmusementPark15 };
paths['aquarium-11'] = { paths: pathsAquarium11 };
paths['aquarium-15'] = { paths: pathsAquarium15 };
paths['art-gallery-11'] = { paths: pathsArtGallery11 };
paths['art-gallery-15'] = { paths: pathsArtGallery15 };
paths['attraction-11'] = { paths: pathsAttraction11 };
paths['attraction-15'] = { paths: pathsAttraction15 };
paths['bakery-11'] = { paths: pathsBakery11 };
paths['bakery-15'] = { paths: pathsBakery15 };
paths['bank-11'] = { paths: pathsBank11 };
paths['bank-15'] = { paths: pathsBank15 };
paths['bank-JP-11'] = { paths: pathsBankJp11 };
paths['bank-JP-15'] = { paths: pathsBankJp15 };
paths['bar-11'] = { paths: pathsBar11 };
paths['bar-15'] = { paths: pathsBar15 };
paths['barrier-11'] = { paths: pathsBarrier11 };
paths['barrier-15'] = { paths: pathsBarrier15 };
paths['baseball-11'] = { paths: pathsBaseball11 };
paths['baseball-15'] = { paths: pathsBaseball15 };
paths['basketball-11'] = { paths: pathsBasketball11 };
paths['basketball-15'] = { paths: pathsBasketball15 };
paths['bbq-11'] = { paths: pathsBbq11 };
paths['bbq-15'] = { paths: pathsBbq15 };
paths['beach-11'] = { paths: pathsBeach11 };
paths['beach-15'] = { paths: pathsBeach15 };
paths['beer-11'] = { paths: pathsBeer11 };
paths['beer-15'] = { paths: pathsBeer15 };
paths['bicycle-11'] = { paths: pathsBicycle11 };
paths['bicycle-15'] = { paths: pathsBicycle15 };
paths['bicycle-share-11'] = { paths: pathsBicycleShare11 };
paths['bicycle-share-15'] = { paths: pathsBicycleShare15 };
paths['blood-bank-11'] = { paths: pathsBloodBank11 };
paths['blood-bank-15'] = { paths: pathsBloodBank15 };
paths['bowling-alley-11'] = { paths: pathsBowlingAlley11 };
paths['bowling-alley-15'] = { paths: pathsBowlingAlley15 };
paths['bridge-11'] = { paths: pathsBridge11 };
paths['bridge-15'] = { paths: pathsBridge15 };
paths['building-11'] = { paths: pathsBuilding11 };
paths['building-15'] = { paths: pathsBuilding15 };
paths['building-alt1-11'] = { paths: pathsBuildingAlt111 };
paths['building-alt1-15'] = { paths: pathsBuildingAlt115 };
paths['bus-11'] = { paths: pathsBus11 };
paths['bus-15'] = { paths: pathsBus15 };
paths['cafe-11'] = { paths: pathsCafe11 };
paths['cafe-15'] = { paths: pathsCafe15 };
paths['campsite-11'] = { paths: pathsCampsite11 };
paths['campsite-15'] = { paths: pathsCampsite15 };
paths['car-11'] = { paths: pathsCar11 };
paths['car-15'] = { paths: pathsCar15 };
paths['car-rental-11'] = { paths: pathsCarRental11 };
paths['car-rental-15'] = { paths: pathsCarRental15 };
paths['car-repair-11'] = { paths: pathsCarRepair11 };
paths['car-repair-15'] = { paths: pathsCarRepair15 };
paths['casino-11'] = { paths: pathsCasino11 };
paths['casino-15'] = { paths: pathsCasino15 };
paths['castle-11'] = { paths: pathsCastle11 };
paths['castle-15'] = { paths: pathsCastle15 };
paths['castle-JP-11'] = { paths: pathsCastleJp11 };
paths['castle-JP-15'] = { paths: pathsCastleJp15 };
paths['cemetery-11'] = { paths: pathsCemetery11 };
paths['cemetery-15'] = { paths: pathsCemetery15 };
paths['cemetery-JP-11'] = { paths: pathsCemeteryJp11 };
paths['cemetery-JP-15'] = { paths: pathsCemeteryJp15 };
paths['charging-station-11'] = { paths: pathsChargingStation11 };
paths['charging-station-15'] = { paths: pathsChargingStation15 };
paths['cinema-11'] = { paths: pathsCinema11 };
paths['cinema-15'] = { paths: pathsCinema15 };
paths['circle-11'] = { paths: pathsCircle11 };
paths['circle-15'] = { paths: pathsCircle15 };
paths['circle-stroked-11'] = { paths: pathsCircleStroked11 };
paths['circle-stroked-15'] = { paths: pathsCircleStroked15 };
paths['city-11'] = { paths: pathsCity11 };
paths['city-15'] = { paths: pathsCity15 };
paths['clothing-store-11'] = { paths: pathsClothingStore11 };
paths['clothing-store-15'] = { paths: pathsClothingStore15 };
paths['college-11'] = { paths: pathsCollege11 };
paths['college-15'] = { paths: pathsCollege15 };
paths['college-JP-11'] = { paths: pathsCollegeJp11 };
paths['college-JP-15'] = { paths: pathsCollegeJp15 };
paths['commercial-11'] = { paths: pathsCommercial11 };
paths['commercial-15'] = { paths: pathsCommercial15 };
paths['communications-tower-11'] = { paths: pathsCommunicationsTower11 };
paths['communications-tower-15'] = { paths: pathsCommunicationsTower15 };
paths['confectionery-11'] = { paths: pathsConfectionery11 };
paths['confectionery-15'] = { paths: pathsConfectionery15 };
paths['convenience-11'] = { paths: pathsConvenience11 };
paths['convenience-15'] = { paths: pathsConvenience15 };
paths['cricket-11'] = { paths: pathsCricket11 };
paths['cricket-15'] = { paths: pathsCricket15 };
paths['cross-11'] = { paths: pathsCross11 };
paths['cross-15'] = { paths: pathsCross15 };
paths['dam-11'] = { paths: pathsDam11 };
paths['dam-15'] = { paths: pathsDam15 };
paths['danger-11'] = { paths: pathsDanger11 };
paths['danger-15'] = { paths: pathsDanger15 };
paths['defibrillator-11'] = { paths: pathsDefibrillator11 };
paths['defibrillator-15'] = { paths: pathsDefibrillator15 };
paths['dentist-11'] = { paths: pathsDentist11 };
paths['dentist-15'] = { paths: pathsDentist15 };
paths['doctor-11'] = { paths: pathsDoctor11 };
paths['doctor-15'] = { paths: pathsDoctor15 };
paths['dog-park-11'] = { paths: pathsDogPark11 };
paths['dog-park-15'] = { paths: pathsDogPark15 };
paths['drinking-water-11'] = { paths: pathsDrinkingWater11 };
paths['drinking-water-15'] = { paths: pathsDrinkingWater15 };
paths['embassy-11'] = { paths: pathsEmbassy11 };
paths['embassy-15'] = { paths: pathsEmbassy15 };
paths['emergency-phone-11'] = { paths: pathsEmergencyPhone11 };
paths['emergency-phone-15'] = { paths: pathsEmergencyPhone15 };
paths['entrance-11'] = { paths: pathsEntrance11 };
paths['entrance-15'] = { paths: pathsEntrance15 };
paths['entrance-alt1-11'] = { paths: pathsEntranceAlt111 };
paths['entrance-alt1-15'] = { paths: pathsEntranceAlt115 };
paths['farm-11'] = { paths: pathsFarm11 };
paths['farm-15'] = { paths: pathsFarm15 };
paths['fast-food-11'] = { paths: pathsFastFood11 };
paths['fast-food-15'] = { paths: pathsFastFood15 };
paths['fence-11'] = { paths: pathsFence11 };
paths['fence-15'] = { paths: pathsFence15 };
paths['ferry-11'] = { paths: pathsFerry11 };
paths['ferry-15'] = { paths: pathsFerry15 };
paths['fire-station-11'] = { paths: pathsFireStation11 };
paths['fire-station-15'] = { paths: pathsFireStation15 };
paths['fire-station-JP-11'] = { paths: pathsFireStationJp11 };
paths['fire-station-JP-15'] = { paths: pathsFireStationJp15 };
paths['fitness-centre-11'] = { paths: pathsFitnessCentre11 };
paths['fitness-centre-15'] = { paths: pathsFitnessCentre15 };
paths['florist-11'] = { paths: pathsFlorist11 };
paths['florist-15'] = { paths: pathsFlorist15 };
paths['fuel-11'] = { paths: pathsFuel11 };
paths['fuel-15'] = { paths: pathsFuel15 };
paths['furniture-11'] = { paths: pathsFurniture11 };
paths['furniture-15'] = { paths: pathsFurniture15 };
paths['gaming-11'] = { paths: pathsGaming11 };
paths['gaming-15'] = { paths: pathsGaming15 };
paths['garden-11'] = { paths: pathsGarden11 };
paths['garden-15'] = { paths: pathsGarden15 };
paths['garden-centre-11'] = { paths: pathsGardenCentre11 };
paths['garden-centre-15'] = { paths: pathsGardenCentre15 };
paths['gift-11'] = { paths: pathsGift11 };
paths['gift-15'] = { paths: pathsGift15 };
paths['globe-11'] = { paths: pathsGlobe11 };
paths['globe-15'] = { paths: pathsGlobe15 };
paths['golf-11'] = { paths: pathsGolf11 };
paths['golf-15'] = { paths: pathsGolf15 };
paths['grocery-11'] = { paths: pathsGrocery11 };
paths['grocery-15'] = { paths: pathsGrocery15 };
paths['hairdresser-11'] = { paths: pathsHairdresser11 };
paths['hairdresser-15'] = { paths: pathsHairdresser15 };
paths['harbor-11'] = { paths: pathsHarbor11 };
paths['harbor-15'] = { paths: pathsHarbor15 };
paths['hardware-11'] = { paths: pathsHardware11 };
paths['hardware-15'] = { paths: pathsHardware15 };
paths['heart-11'] = { paths: pathsHeart11 };
paths['heart-15'] = { paths: pathsHeart15 };
paths['heliport-11'] = { paths: pathsHeliport11 };
paths['heliport-15'] = { paths: pathsHeliport15 };
paths['home-11'] = { paths: pathsHome11 };
paths['home-15'] = { paths: pathsHome15 };
paths['horse-riding-11'] = { paths: pathsHorseRiding11 };
paths['horse-riding-15'] = { paths: pathsHorseRiding15 };
paths['hospital-11'] = { paths: pathsHospital11 };
paths['hospital-15'] = { paths: pathsHospital15 };
paths['hospital-JP-11'] = { paths: pathsHospitalJp11 };
paths['hospital-JP-15'] = { paths: pathsHospitalJp15 };
paths['ice-cream-11'] = { paths: pathsIceCream11 };
paths['ice-cream-15'] = { paths: pathsIceCream15 };
paths['industry-11'] = { paths: pathsIndustry11 };
paths['industry-15'] = { paths: pathsIndustry15 };
paths['information-11'] = { paths: pathsInformation11 };
paths['information-15'] = { paths: pathsInformation15 };
paths['jewelry-store-11'] = { paths: pathsJewelryStore11 };
paths['jewelry-store-15'] = { paths: pathsJewelryStore15 };
paths['karaoke-11'] = { paths: pathsKaraoke11 };
paths['karaoke-15'] = { paths: pathsKaraoke15 };
paths['landmark-11'] = { paths: pathsLandmark11 };
paths['landmark-15'] = { paths: pathsLandmark15 };
paths['landmark-JP-11'] = { paths: pathsLandmarkJp11 };
paths['landmark-JP-15'] = { paths: pathsLandmarkJp15 };
paths['landuse-11'] = { paths: pathsLanduse11 };
paths['landuse-15'] = { paths: pathsLanduse15 };
paths['laundry-11'] = { paths: pathsLaundry11 };
paths['laundry-15'] = { paths: pathsLaundry15 };
paths['library-11'] = { paths: pathsLibrary11 };
paths['library-15'] = { paths: pathsLibrary15 };
paths['lighthouse-11'] = { paths: pathsLighthouse11 };
paths['lighthouse-15'] = { paths: pathsLighthouse15 };
paths['lodging-11'] = { paths: pathsLodging11 };
paths['lodging-15'] = { paths: pathsLodging15 };
paths['logging-11'] = { paths: pathsLogging11 };
paths['logging-15'] = { paths: pathsLogging15 };
paths['marker-11'] = { paths: pathsMarker11 };
paths['marker-15'] = { paths: pathsMarker15 };
paths['marker-stroked-11'] = { paths: pathsMarkerStroked11 };
paths['marker-stroked-15'] = { paths: pathsMarkerStroked15 };
paths['mobile-phone-11'] = { paths: pathsMobilePhone11 };
paths['mobile-phone-15'] = { paths: pathsMobilePhone15 };
paths['monument-11'] = { paths: pathsMonument11 };
paths['monument-15'] = { paths: pathsMonument15 };
paths['mountain-11'] = { paths: pathsMountain11 };
paths['mountain-15'] = { paths: pathsMountain15 };
paths['museum-11'] = { paths: pathsMuseum11 };
paths['museum-15'] = { paths: pathsMuseum15 };
paths['music-11'] = { paths: pathsMusic11 };
paths['music-15'] = { paths: pathsMusic15 };
paths['natural-11'] = { paths: pathsNatural11 };
paths['natural-15'] = { paths: pathsNatural15 };
paths['optician-11'] = { paths: pathsOptician11 };
paths['optician-15'] = { paths: pathsOptician15 };
paths['paint-11'] = { paths: pathsPaint11 };
paths['paint-15'] = { paths: pathsPaint15 };
paths['park-11'] = { paths: pathsPark11 };
paths['park-15'] = { paths: pathsPark15 };
paths['park-alt1-11'] = { paths: pathsParkAlt111 };
paths['park-alt1-15'] = { paths: pathsParkAlt115 };
paths['parking-11'] = { paths: pathsParking11 };
paths['parking-15'] = { paths: pathsParking15 };
paths['parking-garage-11'] = { paths: pathsParkingGarage11 };
paths['parking-garage-15'] = { paths: pathsParkingGarage15 };
paths['pharmacy-11'] = { paths: pathsPharmacy11 };
paths['pharmacy-15'] = { paths: pathsPharmacy15 };
paths['picnic-site-11'] = { paths: pathsPicnicSite11 };
paths['picnic-site-15'] = { paths: pathsPicnicSite15 };
paths['pitch-11'] = { paths: pathsPitch11 };
paths['pitch-15'] = { paths: pathsPitch15 };
paths['place-of-worship-11'] = { paths: pathsPlaceOfWorship11 };
paths['place-of-worship-15'] = { paths: pathsPlaceOfWorship15 };
paths['playground-11'] = { paths: pathsPlayground11 };
paths['playground-15'] = { paths: pathsPlayground15 };
paths['police-11'] = { paths: pathsPolice11 };
paths['police-15'] = { paths: pathsPolice15 };
paths['police-JP-11'] = { paths: pathsPoliceJp11 };
paths['police-JP-15'] = { paths: pathsPoliceJp15 };
paths['post-11'] = { paths: pathsPost11 };
paths['post-15'] = { paths: pathsPost15 };
paths['post-JP-11'] = { paths: pathsPostJp11 };
paths['post-JP-15'] = { paths: pathsPostJp15 };
paths['prison-11'] = { paths: pathsPrison11 };
paths['prison-15'] = { paths: pathsPrison15 };
paths['rail-11'] = { paths: pathsRail11 };
paths['rail-15'] = { paths: pathsRail15 };
paths['rail-light-11'] = { paths: pathsRailLight11 };
paths['rail-light-15'] = { paths: pathsRailLight15 };
paths['rail-metro-11'] = { paths: pathsRailMetro11 };
paths['rail-metro-15'] = { paths: pathsRailMetro15 };
paths['ranger-station-11'] = { paths: pathsRangerStation11 };
paths['ranger-station-15'] = { paths: pathsRangerStation15 };
paths['recycling-11'] = { paths: pathsRecycling11 };
paths['recycling-15'] = { paths: pathsRecycling15 };
paths['religious-buddhist-11'] = { paths: pathsReligiousBuddhist11 };
paths['religious-buddhist-15'] = { paths: pathsReligiousBuddhist15 };
paths['religious-christian-11'] = { paths: pathsReligiousChristian11 };
paths['religious-christian-15'] = { paths: pathsReligiousChristian15 };
paths['religious-jewish-11'] = { paths: pathsReligiousJewish11 };
paths['religious-jewish-15'] = { paths: pathsReligiousJewish15 };
paths['religious-muslim-11'] = { paths: pathsReligiousMuslim11 };
paths['religious-muslim-15'] = { paths: pathsReligiousMuslim15 };
paths['religious-shinto-11'] = { paths: pathsReligiousShinto11 };
paths['religious-shinto-15'] = { paths: pathsReligiousShinto15 };
paths['residential-community-11'] = { paths: pathsResidentialCommunity11 };
paths['residential-community-15'] = { paths: pathsResidentialCommunity15 };
paths['restaurant-11'] = { paths: pathsRestaurant11 };
paths['restaurant-15'] = { paths: pathsRestaurant15 };
paths['restaurant-noodle-11'] = { paths: pathsRestaurantNoodle11 };
paths['restaurant-noodle-15'] = { paths: pathsRestaurantNoodle15 };
paths['restaurant-pizza-11'] = { paths: pathsRestaurantPizza11 };
paths['restaurant-pizza-15'] = { paths: pathsRestaurantPizza15 };
paths['restaurant-seafood-11'] = { paths: pathsRestaurantSeafood11 };
paths['restaurant-seafood-15'] = { paths: pathsRestaurantSeafood15 };
paths['roadblock-11'] = { paths: pathsRoadblock11 };
paths['roadblock-15'] = { paths: pathsRoadblock15 };
paths['rocket-11'] = { paths: pathsRocket11 };
paths['rocket-15'] = { paths: pathsRocket15 };
paths['school-11'] = { paths: pathsSchool11 };
paths['school-15'] = { paths: pathsSchool15 };
paths['school-JP-11'] = { paths: pathsSchoolJp11 };
paths['school-JP-15'] = { paths: pathsSchoolJp15 };
paths['scooter-11'] = { paths: pathsScooter11 };
paths['scooter-15'] = { paths: pathsScooter15 };
paths['shelter-11'] = { paths: pathsShelter11 };
paths['shelter-15'] = { paths: pathsShelter15 };
paths['shoe-11'] = { paths: pathsShoe11 };
paths['shoe-15'] = { paths: pathsShoe15 };
paths['shop-11'] = { paths: pathsShop11 };
paths['shop-15'] = { paths: pathsShop15 };
paths['skateboard-11'] = { paths: pathsSkateboard11 };
paths['skateboard-15'] = { paths: pathsSkateboard15 };
paths['skiing-11'] = { paths: pathsSkiing11 };
paths['skiing-15'] = { paths: pathsSkiing15 };
paths['slaughterhouse-11'] = { paths: pathsSlaughterhouse11 };
paths['slaughterhouse-15'] = { paths: pathsSlaughterhouse15 };
paths['slipway-11'] = { paths: pathsSlipway11 };
paths['slipway-15'] = { paths: pathsSlipway15 };
paths['snowmobile-11'] = { paths: pathsSnowmobile11 };
paths['snowmobile-15'] = { paths: pathsSnowmobile15 };
paths['soccer-11'] = { paths: pathsSoccer11 };
paths['soccer-15'] = { paths: pathsSoccer15 };
paths['square-11'] = { paths: pathsSquare11 };
paths['square-15'] = { paths: pathsSquare15 };
paths['square-stroked-11'] = { paths: pathsSquareStroked11 };
paths['square-stroked-15'] = { paths: pathsSquareStroked15 };
paths['stadium-11'] = { paths: pathsStadium11 };
paths['stadium-15'] = { paths: pathsStadium15 };
paths['star-11'] = { paths: pathsStar11 };
paths['star-15'] = { paths: pathsStar15 };
paths['star-stroked-11'] = { paths: pathsStarStroked11 };
paths['star-stroked-15'] = { paths: pathsStarStroked15 };
paths['suitcase-11'] = { paths: pathsSuitcase11 };
paths['suitcase-15'] = { paths: pathsSuitcase15 };
paths['sushi-11'] = { paths: pathsSushi11 };
paths['sushi-15'] = { paths: pathsSushi15 };
paths['swimming-11'] = { paths: pathsSwimming11 };
paths['swimming-15'] = { paths: pathsSwimming15 };
paths['table-tennis-11'] = { paths: pathsTableTennis11 };
paths['table-tennis-15'] = { paths: pathsTableTennis15 };
paths['teahouse-11'] = { paths: pathsTeahouse11 };
paths['teahouse-15'] = { paths: pathsTeahouse15 };
paths['telephone-11'] = { paths: pathsTelephone11 };
paths['telephone-15'] = { paths: pathsTelephone15 };
paths['tennis-11'] = { paths: pathsTennis11 };
paths['tennis-15'] = { paths: pathsTennis15 };
paths['theatre-11'] = { paths: pathsTheatre11 };
paths['theatre-15'] = { paths: pathsTheatre15 };
paths['toilet-11'] = { paths: pathsToilet11 };
paths['toilet-15'] = { paths: pathsToilet15 };
paths['town-11'] = { paths: pathsTown11 };
paths['town-15'] = { paths: pathsTown15 };
paths['town-hall-11'] = { paths: pathsTownHall11 };
paths['town-hall-15'] = { paths: pathsTownHall15 };
paths['triangle-11'] = { paths: pathsTriangle11 };
paths['triangle-15'] = { paths: pathsTriangle15 };
paths['triangle-stroked-11'] = { paths: pathsTriangleStroked11 };
paths['triangle-stroked-15'] = { paths: pathsTriangleStroked15 };
paths['veterinary-11'] = { paths: pathsVeterinary11 };
paths['veterinary-15'] = { paths: pathsVeterinary15 };
paths['viewpoint-11'] = { paths: pathsViewpoint11 };
paths['viewpoint-15'] = { paths: pathsViewpoint15 };
paths['village-11'] = { paths: pathsVillage11 };
paths['village-15'] = { paths: pathsVillage15 };
paths['volcano-11'] = { paths: pathsVolcano11 };
paths['volcano-15'] = { paths: pathsVolcano15 };
paths['volleyball-11'] = { paths: pathsVolleyball11 };
paths['volleyball-15'] = { paths: pathsVolleyball15 };
paths['warehouse-11'] = { paths: pathsWarehouse11 };
paths['warehouse-15'] = { paths: pathsWarehouse15 };
paths['waste-basket-11'] = { paths: pathsWasteBasket11 };
paths['waste-basket-15'] = { paths: pathsWasteBasket15 };
paths['watch-11'] = { paths: pathsWatch11 };
paths['watch-15'] = { paths: pathsWatch15 };
paths['water-11'] = { paths: pathsWater11 };
paths['water-15'] = { paths: pathsWater15 };
paths['waterfall-11'] = { paths: pathsWaterfall11 };
paths['waterfall-15'] = { paths: pathsWaterfall15 };
paths['watermill-11'] = { paths: pathsWatermill11 };
paths['watermill-15'] = { paths: pathsWatermill15 };
paths['wetland-11'] = { paths: pathsWetland11 };
paths['wetland-15'] = { paths: pathsWetland15 };
paths['wheelchair-11'] = { paths: pathsWheelchair11 };
paths['wheelchair-15'] = { paths: pathsWheelchair15 };
paths['windmill-11'] = { paths: pathsWindmill11 };
paths['windmill-15'] = { paths: pathsWindmill15 };
paths['zoo-11'] = { paths: pathsZoo11 };
paths['zoo-15'] = { paths: pathsZoo15 };
export const iconsMap = paths;
